export interface ProductFile {
  name: string;
  sizeMB: number;
}

export type ProductCategory = "original" | "notes-bundle" | "teacher-brand" | "test-series" | "optional";

export interface StoreProduct {
  slug: string;
  title: string;
  tagline: string;
  description: string;
  longDescription: string[];
  price: number;
  originalPrice: number | null;
  rating: number | null;
  reviewCount: number | null;
  badge: string;
  badgeColor: "emerald" | "amber" | "gray";
  gradient: string;
  features: string[];
  payNote: string;
  payAmount: number;
  link: string | null;
  comingSoon: boolean;
  institute?: string;
  category?: ProductCategory;
  image?: string;
  fileCount?: number;
  totalSizeMB?: number;
  files?: ProductFile[];
}

export interface Institute {
  slug: string;
  name: string;
  shortName: string;
  description: string;
  gradient: string;
  logo: string;
}

export const INSTITUTES: Institute[] = [
  {
    slug: "insight-ias",
    name: "Insight IAS",
    shortName: "Insight IAS",
    description: "Prelims test series and study material",
    gradient: "bg-blue-600",
    logo: "/images/institutes/insight-ias.png",
  },
  {
    slug: "only-ias",
    name: "Only IAS",
    shortName: "Only IAS",
    description: "Prelims test series",
    gradient: "bg-orange-500",
    logo: "/images/institutes/only-ias.png",
  },
  {
    slug: "ias-baba",
    name: "IAS BABA",
    shortName: "IAS BABA",
    description: "All India Open Mock Tests and Mains tests",
    gradient: "bg-emerald-600",
    logo: "/images/institutes/ias-baba.png",
  },
  {
    slug: "csk-csat",
    name: "CSK's CSAT",
    shortName: "CSK CSAT",
    description: "CSAT micro tests and practice sets",
    gradient: "bg-purple-600",
    logo: "CS",
  },
  {
    slug: "sudarshan-gurjar",
    name: "Sudarshan Gurjar",
    shortName: "Sudarshan Gurjar",
    description: "Places in News and geography compilations",
    gradient: "bg-cyan-600",
    logo: "/images/institutes/sudarshan-gurjar.png",
  },
  {
    slug: "general",
    name: "General Compilations",
    shortName: "Compilations",
    description: "Government schemes, PYQ analysis, and more",
    gradient: "bg-rose-600",
    logo: "GC",
  },
];

export const PRODUCTS: StoreProduct[] = [
  {
    slug: "top-10-rankers-strategy",
    title: "Top 10 Rankers Strategy",
    image: "/images/products/top-10-rankers-strategy.png",
    tagline: "AIR 1-10 complete strategies in one PDF",
    description: "Full strategies, marks analysis, paper-by-paper breakdowns, and score deep dives for AIR 1 through AIR 10.",
    longDescription: [
      "This compilation brings together the complete preparation strategies of the top 10 rank holders from recent UPSC CSE cycles. Every strategy is distilled from their interviews and published content, paired with verified marks from official UPSC records.",
      "You get paper-wise marks analysis with visual score charts, a score deep dive showing strongest and weakest papers, and key observations that reveal what actually worked for each topper.",
      "The report is formatted as a branded 8-page PDF, ready to save, print, or read on any device.",
    ],
    price: 299,
    originalPrice: 990,
    rating: 4.8,
    reviewCount: 24,
    badge: "Most Popular",
    badgeColor: "emerald",
    gradient: "from-purple-600 via-purple-500 to-indigo-500",
    features: [
      "Complete strategy distilled from interviews and published content",
      "Paper-wise marks analysis with visual score charts",
      "Score deep dive: strongest paper, weakest paper, contribution %",
      "Key takeaways from each topper's UPSC journey",
      "Branded 8-page PDF, ready to save or print",
    ],
    category: "original",
    payNote: "Top 10 Rankers Strategy Compilation",
    payAmount: 299,
    link: null,
    comingSoon: false,
  },
  {
    slug: "all-strategy-reports",
    title: "All Strategy Reports",
    image: "/images/products/all-strategy-reports.png",
    tagline: "All 280+ topper strategies bundled",
    description: "Every topper's complete strategy, marks analysis, and paper breakdown in one bundle.",
    longDescription: [
      "Get access to every strategy report in the UPSCPrepNotes library. This bundle includes the complete strategy, marks analysis, and paper breakdown for each of the 280+ topper profiles on the platform.",
      "Every report is built from verified UPSC data and the topper's own interviews. You get paper-wise marks, score deep dives, and key observations for every rank holder.",
      "One payment, lifetime access. New topper profiles are added automatically as they are published.",
    ],
    price: 799,
    originalPrice: 27720,
    rating: 4.7,
    reviewCount: 18,
    badge: "Best Value",
    badgeColor: "emerald",
    gradient: "from-emerald-600 via-emerald-500 to-teal-500",
    features: [
      "280+ complete strategy reports with marks analysis",
      "Paper-wise breakdowns and score deep dives for every topper",
      "One payment, lifetime access with automatic additions",
      "Branded PDF format, ready to save or print",
      "New reports added as new toppers are published",
    ],
    category: "original",
    payNote: "All Strategy Reports Bundle",
    payAmount: 799,
    link: null,
    comingSoon: false,
  },
  {
    slug: "answer-copies-compilation",
    title: "Answer Copies Compilation",
    image: "/images/products/answer-copies-compilation.png",
    tagline: "50+ handwritten answer sheets",
    description: "Actual handwritten answer sheets from 50+ toppers (AIR 1-1249). GS1-4, Essay, Optional papers.",
    longDescription: [
      "This compilation contains actual scanned answer sheets written by UPSC toppers in the exam hall. See exactly how rank holders structured their answers, used headings, diagrams, and underlining to score 140+.",
      "Covers GS Papers 1-4, Essay, and Optional papers. Each copy is labelled with the topper's name, rank, year, and marks obtained.",
      "Organised by paper and marks so you can compare approaches across different scorers.",
    ],
    price: 799,
    originalPrice: null,
    rating: 4.9,
    reviewCount: 31,
    badge: "Top Rated",
    badgeColor: "amber",
    gradient: "bg-amber-500",
    features: [
      "50+ actual handwritten answer sheets from toppers",
      "Covers GS1-4, Essay, and Optional papers",
      "Each copy labelled with name, rank, year, and marks",
      "See real handwriting, structure, underlining, and diagrams",
      "Organised by paper and marks for easy comparison",
    ],
    category: "original",
    payNote: "Answer Copies Compilation",
    payAmount: 799,
    link: null,
    comingSoon: false,
  },
  {
    slug: "marks-database",
    title: "Marks Database",
    tagline: "Paper-wise marks for every topper",
    description: "Complete marks breakdown for every topper. Filter, compare, and export paper-wise scores.",
    longDescription: [
      "A searchable database of paper-wise marks for every topper in the library. Filter by optional subject, rank range, or year to compare scores across GS1-4, Essay, Optional 1 & 2, Interview, and Written Total.",
      "See how toppers in your optional scored across papers, identify patterns in top performers, and benchmark your own preparation.",
      "Exportable format for offline analysis.",
    ],
    price: 199,
    originalPrice: null,
    rating: null,
    reviewCount: null,
    badge: "Coming Soon",
    badgeColor: "gray",
    gradient: "bg-gray-200",
    features: [
    ],
    category: "original",
    payNote: "Marks Database",
    payAmount: 199,
    link: null,
    comingSoon: true,
  },
  {
    slug: "optional-subject-bundles",
    title: "Optional Subject Bundles",
    tagline: "Strategies grouped by your optional",
    description: "All strategies and marks for toppers in your optional subject. PSIR, Anthropology, Sociology, Geography, and more.",
    longDescription: [
      "Get every strategy report and marks breakdown for toppers who shared your optional subject. See how different rank holders approached the same subject, what resources they used, and what scores they achieved.",
      "Available for PSIR, Anthropology, Sociology, Geography, Mathematics, History, Public Administration, and more subjects as topper data is added.",
    ],
    price: 399,
    originalPrice: null,
    rating: null,
    reviewCount: null,
    badge: "Coming Soon",
    badgeColor: "gray",
    gradient: "bg-gray-200",
    features: [
    ],
    category: "original",
    payNote: "Optional Subject Bundle",
    payAmount: 399,
    link: null,
    comingSoon: true,
  },
  {
    slug: "insight-ias-prelims-tests-1-10",
    title: "Insight IAS Prelims Tests 1-10",
      image: "/images/products/insight-ias-prelims-tests-1-10.png",
    tagline: "Full-length GS Prelims test series by Insight IAS",
    description: "10 full-length GS Prelims tests with answer keys. Covers complete syllabus as per latest UPSC pattern.",
    longDescription: [
      "Set of 10 full-length General Studies Prelims test papers from Insight IAS, one of India's most respected UPSC coaching institutes.",
      "Each test follows the actual UPSC Prelims pattern with 100 questions covering History, Geography, Polity, Economy, Science & Tech, Environment, and Current Affairs.",
      "Includes detailed answer keys with explanations for every question.",
    ],
    price: 199,
    originalPrice: 999,
    rating: null,
    reviewCount: null,
    badge: "10 Tests",
    badgeColor: "emerald",
    gradient: "bg-blue-600",
    features: [
      "10 full-length GS Prelims tests",
      "100 questions per test — UPSC pattern",
      "Detailed answer keys with explanations",
      "Covers complete Prelims syllabus",
      "Instant PDF download after purchase",
    ],
    category: "test-series",
    payNote: "Insight IAS Prelims Tests 1-10",
    payAmount: 199,
    link: null,
    comingSoon: false,
    institute: "insight-ias",
  },
  {
    slug: "only-ias-pt-tests-1-10",
    title: "Only IAS PT Tests 1-10",
      image: "/images/products/only-ias-pt-tests-1-10.png",
    tagline: "Prelims test series by Only IAS",
    description: "10 full-length Prelims tests designed by Only IAS faculty. Covers GS Paper 1 with detailed solutions.",
    longDescription: [
      "Comprehensive set of 10 Prelims test papers from Only IAS, designed to simulate the actual exam experience.",
      "Each test is curated by experienced faculty and covers the entire GS Prelims syllabus with special focus on high-weightage topics.",
      "Comes with detailed solutions and performance analysis pointers.",
    ],
    price: 199,
    originalPrice: 899,
    rating: null,
    reviewCount: null,
    badge: "10 Tests",
    badgeColor: "emerald",
    gradient: "bg-orange-500",
    features: [
      "10 full-length GS Prelims tests",
      "Exam-pattern questions with varying difficulty",
      "Detailed solutions for every question",
      "Covers entire Prelims syllabus",
      "Instant PDF download",
    ],
    category: "test-series",
    payNote: "Only IAS PT Tests 1-10",
    payAmount: 199,
    link: null,
    comingSoon: false,
    institute: "only-ias",
  },
  {
    slug: "ias-baba-aiomt-1-3",
    title: "IAS BABA AIOMT 1-3",
      image: "/images/products/ias-baba-aiomt-1-3.png",
    tagline: "AIOMT series by IAS BABA — Prelims",
    description: "3 All India Open Mock Tests for GS Prelims. Benchmark your preparation against thousands of aspirants.",
    longDescription: [
      "IAS BABA's All India Open Mock Tests are among the most attempted test series by UPSC aspirants. These 3 tests cover the complete GS Prelims syllabus with UPSC-standard difficulty.",
      "Each test includes 100 questions with detailed explanations, designed to help you identify weak areas and improve your attempt strategy.",
      "Perfect for self-assessment in the final phase of Prelims preparation.",
    ],
    price: 99,
    originalPrice: 499,
    rating: null,
    reviewCount: null,
    badge: "3 Tests",
    badgeColor: "amber",
    gradient: "bg-emerald-600",
    image: "/images/products/ias-baba-aiomt-1-3.png",
    features: [
      "3 All India Open Mock Tests",
      "UPSC-standard difficulty level",
      "Detailed answer key with explanations",
      "Covers full GS Prelims syllabus",
      "Instant PDF download",
    ],
    category: "test-series",
    payNote: "IAS BABA AIOMT 1-3",
    payAmount: 99,
    link: null,
    comingSoon: false,
    institute: "ias-baba",
  },
  {
    slug: "ias-baba-mains-tests-1-5",
    title: "IAS BABA Mains Tests 1-5",
      image: "/images/products/ias-baba-mains-tests-1-5.png",
    tagline: "GS Mains answer writing practice by IAS BABA",
    description: "5 full-length GS Mains test papers covering GS 1-4. Essential for Mains answer writing practice.",
    longDescription: [
      "Set of 5 full-length General Studies Mains test papers from IAS BABA, covering GS Papers 1 through 4.",
      "Each test follows the actual UPSC Mains pattern with questions designed to test conceptual clarity, analytical ability, and answer presentation.",
      "Includes model answers and marking schemes for self-evaluation.",
    ],
    price: 149,
    originalPrice: 749,
    rating: null,
    reviewCount: null,
    badge: "5 Tests",
    badgeColor: "emerald",
    gradient: "bg-emerald-700",
    image: "/images/products/ias-baba-mains-tests-1-5.png",
    features: [
      "5 full-length GS Mains tests (GS 1-4)",
      "UPSC Mains pattern questions",
      "Model answers and marking scheme",
      "Covers complete Mains syllabus",
      "Instant PDF download",
    ],
    category: "test-series",
    payNote: "IAS BABA Mains Tests 1-5",
    payAmount: 149,
    link: null,
    comingSoon: false,
    institute: "ias-baba",
  },
  {
    slug: "csk-csat-micro-tests-1-16",
    title: "CSK's CSAT Micro Tests 1-16",
      image: "/images/products/csk-csat-micro-tests-1-16.png",
    tagline: "Complete CSAT practice with 16 topic-wise micro tests",
    description: "16 micro tests covering all CSAT topics — comprehension, reasoning, maths, and data interpretation.",
    longDescription: [
      "CSK's CSAT Micro Tests are designed to help you master the CSAT paper through focused topic-wise practice. 16 tests covering every CSAT topic in detail.",
      "Topics include: Reading Comprehension, Logical Reasoning, Quantitative Aptitude, Data Interpretation, and Verbal Ability.",
      "Each test comes with detailed solutions and time-management tips. Ideal for building speed and accuracy.",
    ],
    price: 149,
    originalPrice: 599,
    rating: null,
    reviewCount: null,
    badge: "16 Tests",
    badgeColor: "emerald",
    gradient: "bg-purple-600",
    image: "/images/products/csk-csat-micro-tests-1-16.png",
    features: [
      "16 topic-wise CSAT micro tests",
      "Covers comprehension, reasoning, maths, DI",
      "Detailed solutions for every question",
      "Focus on speed and accuracy building",
      "Instant PDF download",
    ],
    category: "test-series",
    payNote: "CSK CSAT Micro Tests 1-16",
    payAmount: 149,
    link: null,
    comingSoon: false,
    institute: "csk-csat",
  },
  {
    slug: "places-in-news",
    title: "Places in News",
    image: "/images/products/places-in-news.png",
    tagline: "Complete Places in News compilation by Sudarshan Gurjar",
    description: "Comprehensive compilation of all places in news for UPSC — geography, current affairs, and map-based questions covered.",
    longDescription: [
      "Sudarshan Gurjar's 'Places in News' is a must-have compilation for every UPSC aspirant. It covers every geographic location that appeared in the news, organized by region and topic.",
      "Each entry includes the location's geographic significance, why it was in the news, and key facts relevant for Prelims and Mains.",
      "Perfect for revising map-based questions and geography current affairs in one go.",
    ],
    price: 99,
    originalPrice: null,
    rating: null,
    reviewCount: null,
    badge: "Bestseller",
    badgeColor: "amber",
    gradient: "bg-cyan-600",
    features: [
      "Complete Places in News compilation",
      "Organized by region and topic",
      "Key facts for Prelims and Mains",
      "Map-based question preparation",
      "Instant PDF download",
    ],
    category: "original",
    payNote: "Places in News by Sudarshan Gurjar",
    payAmount: 99,
    link: null,
    comingSoon: false,
    institute: "sudarshan-gurjar",
  },
  {
    slug: "government-schemes-compilation",
    title: "Government Schemes Compilation",
    image: "/images/products/government-schemes-compilation.png",
    tagline: "All important government schemes for UPSC 2026",
    description: "Comprehensive compilation of all central government schemes, categorized by ministry and sector.",
    longDescription: [
      "A complete compilation of all important government schemes relevant for UPSC CSE 2026. Each scheme is summarized with its objective, features, budget, and target beneficiaries.",
      "Organized by ministry and sector — education, health, agriculture, rural development, social welfare, and more.",
      "Ideal for both Prelims (scheme-based questions) and Mains (governance and social justice) preparation.",
    ],
    price: 99,
    originalPrice: null,
    rating: null,
    reviewCount: null,
    badge: "Popular",
    badgeColor: "amber",
    gradient: "bg-rose-600",
    features: [
      "All important schemes covered",
      "Organized by ministry and sector",
      "Objective, features, budget, beneficiaries",
      "Prelims and Mains focused",
      "Instant PDF download",
    ],
    category: "original",
    payNote: "Government Schemes Compilation",
    payAmount: 99,
    link: null,
    comingSoon: false,
    institute: "general",
  },
  {
    slug: "gs1-notes-bundle",
    title: "GS 1 Complete Notes Bundle",
      image: "/images/products/gs1-notes-bundle.png",
    tagline: "22 comprehensive notes for GS 1 Mains",
    description: "Complete GS 1 notes compilation featuring topper and teacher notes covering Indian Heritage & Culture, Modern & World History, Geography, and Indian Society.",
    longDescription: [
      "GS 1 is the broadest Mains paper, covering Indian Heritage & Culture, Modern & World History, Geography of India & World, and Indian Society. This bundle brings together the best notes from multiple toppers and teachers into one comprehensive set.",
      "Includes notes from Madhav (AIR 16), Asad Zuberi (AIR 86), Satyam Gandhi (AIR 82), PRAHAAR, Antriksh, Abhijit Ray, and more. Covers every GS 1 topic in depth.",
      "With 22 files spanning 778 MB, this is the most complete GS 1 notes compilation available.",
    ],
    price: 199,
    originalPrice: 499,
    rating: null,
    reviewCount: null,
    badge: "22 Files",
    badgeColor: "emerald",
    gradient: "bg-blue-700",
    features: [
      "22 comprehensive notes files",
      "Covers Art & Culture, History, Geography, Society",
      "Topper & teacher notes from Madhav, Asad Zuberi, Satyam Gandhi, PRAHAAR, Antriksh",
      "Includes AIR 10, AIR 16, AIR 82, AIR 86 notes",
      "Instant PDF download",
    ],
    category: "notes-bundle",
    payNote: "GS 1 Complete Notes Bundle",
    payAmount: 199,
    link: null,
    comingSoon: false,
    image: "/images/products/gs1-notes-bundle.png",
    fileCount: 22,
    totalSizeMB: 778,
    files: [
      { name: "AIR 10 MAINS NOTES GS 1.pdf", sizeMB: 33.0 },
      { name: "AIR 10 MAINS NOTES GS 2.pdf", sizeMB: 76.0 },
      { name: "AIR 10 MAINS NOTES GS 3.pdf", sizeMB: 67.6 },
      { name: "AZ GS1 Evaluated.pdf", sizeMB: 38.5 },
      { name: "AZ GS1-1.pdf", sizeMB: 31.2 },
      { name: "AZ GS1-2.pdf", sizeMB: 25.9 },
      { name: "Abhijit_Ray_ancient_medeival_art_culture_notes_pre_and_mains_combined.pdf", sizeMB: 70.3 },
      { name: "ArtCulture_Notes.pdf", sizeMB: 56.5 },
      { name: "GS-1 Notes_and_Essay_Satyam_Gandhi.pdf", sizeMB: 124.3 },
      { name: "GS1_Art_&_Culture_Madhav_AIR16_CSE24_(with_Ratnesh).pdf", sizeMB: 34.7 },
      { name: "GS1_Geography_Madhav_AIR16_CSE24_(with_Ratnesh).pdf", sizeMB: 24.0 },
      { name: "GS1_Modern_Indian_History_Madhav_AIR16_CSE24_(with_Ratnesh).pdf", sizeMB: 5.4 },
    ],
  },
  {
    slug: "gs2-notes-bundle",
    title: "GS 2 Complete Notes Bundle",
      image: "/images/products/gs2-notes-bundle.png",
    tagline: "17 comprehensive notes for GS 2 Mains",
    description: "Complete GS 2 notes compilation covering Indian Polity, Governance, International Relations, and Social Justice from top rankers and teachers.",
    longDescription: [
      "GS 2 covers Polity & Constitution, Governance, Social Justice, and International Relations. This bundle compiles the best notes from multiple toppers and coaching brands.",
      "Includes Madhav (AIR 16), Asad Zuberi (AIR 86), Satyam Gandhi (AIR 82), PRAHAAR, Antriksh, and Polity Foundation notes across 17 files.",
      "From constitutional articles to IR theories, everything you need for GS 2 in one place.",
    ],
    price: 199,
    originalPrice: 499,
    rating: null,
    reviewCount: null,
    badge: "17 Files",
    badgeColor: "emerald",
    gradient: "bg-indigo-600",
    features: [
      "17 comprehensive notes files",
      "Covers Polity, Governance, IR, Social Justice",
      "Topper & teacher notes from Madhav, Asad Zuberi, Satyam Gandhi, PRAHAAR",
      "Polity Foundation included (265 MB)",
      "Instant PDF download",
    ],
    category: "notes-bundle",
    payNote: "GS 2 Complete Notes Bundle",
    payAmount: 199,
    link: null,
    comingSoon: false,
    image: "/images/products/gs2-notes-bundle.png",
    fileCount: 17,
    totalSizeMB: 788,
    files: [
      { name: "AIR 10 MAINS NOTES GS 2.pdf", sizeMB: 76.0 },
      { name: "AZ GS2-1.pdf", sizeMB: 32.5 },
      { name: "GS-2 Notes_Satyam_Gandhi.pdf", sizeMB: 69.2 },
      { name: "GS2 AsadZuberi AIR86.pdf", sizeMB: 75.3 },
      { name: "GS2_Governance_Madhav_AIR16_CSE24_(with_Ratnesh).pdf", sizeMB: 7.4 },
      { name: "GS2_International_Relations_Madhav_AIR16_CSE24_with_Ratnesh.pdf", sizeMB: 6.1 },
      { name: "GS2_Polity_&_Constitution_Madhav_AIR16_CSE24_with_Ratnesh.pdf", sizeMB: 12.6 },
      { name: "GS2_Social_Justice_Madhav_AIR16_CSE24_(with_Ratnesh).pdf", sizeMB: 3.7 },
      { name: "International Relations notes.pdf", sizeMB: 34.0 },
      { name: "PRAHAAR_Governance.pdf", sizeMB: 19.0 },
      { name: "PRAHAAR_Indian Polity and Constitution.pdf", sizeMB: 25.6 },
      { name: "PRAHAAR_International Relations.pdf", sizeMB: 22.4 },
    ],
  },
  {
    slug: "gs3-notes-bundle",
    title: "GS 3 Complete Notes Bundle",
      image: "/images/products/gs3-notes-bundle.png",
    tagline: "19 comprehensive notes for GS 3 Mains",
    description: "Complete GS 3 notes compilation covering Economy, Agriculture, Environment, Science & Tech, Internal Security, and Disaster Management.",
    longDescription: [
      "GS 3 covers the dynamic papers of Economy, Agriculture, Environment, Science & Technology, Internal Security, and Disaster Management. This bundle brings together 19 files from the best sources.",
      "Features Madhav (AIR 16), Asad Zuberi (AIR 86), Satyam Gandhi (AIR 82), PRAHAAR, Antriksh, and the popular Environment Short Notes.",
      "From budget analysis to climate change conventions, cover every GS 3 topic comprehensively.",
    ],
    price: 199,
    originalPrice: 499,
    rating: null,
    reviewCount: null,
    badge: "19 Files",
    badgeColor: "emerald",
    gradient: "bg-emerald-700",
    features: [
      "19 comprehensive notes files",
      "Covers Economy, Agriculture, Environment, S&T, Security, DM",
      "Topper & teacher notes from Madhav, Asad Zuberi, Satyam Gandhi, PRAHAAR, Antriksh",
      "Environment Short Notes included (166 MB)",
      "Instant PDF download",
    ],
    category: "notes-bundle",
    payNote: "GS 3 Complete Notes Bundle",
    payAmount: 199,
    link: null,
    comingSoon: false,
    image: "/images/products/gs3-notes-bundle.png",
    fileCount: 19,
    totalSizeMB: 766,
    files: [
      { name: "AIR 10 MAINS NOTES GS 3.pdf", sizeMB: 67.6 },
      { name: "AZ GS3-1.pdf", sizeMB: 32.6 },
      { name: "AZ GS3-2.pdf", sizeMB: 26.7 },
      { name: "ENVIRONMENT SHORT NOTES.pdf", sizeMB: 166.4 },
      { name: "GS-3 Notes_Satyam_Gandhi.pdf", sizeMB: 120.5 },
      { name: "GS3 AsadZuberiAIR 86.pdf", sizeMB: 60.4 },
      { name: "GS3_Agriculture_Madhav_AIR16_CSE24_(with_Ratnesh).pdf", sizeMB: 10.3 },
      { name: "GS3_Disaster_Management_Madhav_AIR16_CSE24_(with_Ratnesh).pdf", sizeMB: 11.8 },
      { name: "GS3_Economic_Development_Madhav_AIR16_CSE24_(with_Ratnesh).pdf", sizeMB: 13.2 },
      { name: "GS3_Environment_Madhav_AIR16_CSE24_(with_Ratnesh).pdf", sizeMB: 8.0 },
      { name: "GS3_Internal_Security_Madhav_AIR16_CSE24_(with_Ratnesh).pdf", sizeMB: 11.2 },
      { name: "GS3_Science_&_Technology_Madhav_AIR16_CSE24_with_Ratnesh.pdf", sizeMB: 5.5 },
    ],
  },
  {
    slug: "ethics-gs4-bundle",
    title: "Ethics & GS 4 Bundle",
      image: "/images/products/ethics-gs4-bundle.png",
    tagline: "13 comprehensive notes for Ethics, Integrity & Aptitude",
    description: "Complete GS 4 notes covering Ethics theory, case studies, and topper approaches from AIR 9, AIR 10, AIR 16, AIR 86, and PRAHAAR.",
    longDescription: [
      "GS 4 (Ethics, Integrity & Aptitude) requires a unique blend of theory, case studies, and real-world examples. This bundle compiles 13 files from multiple rank holders and teachers.",
      "Includes Ethics notes from AIR 9 (Dr. Apala Mishra), AIR 10, AIR 16 (Madhav), AIR 86 (Asad Zuberi), PRAHAAR, Lukman IAS, and Gunjita.",
      "Covering ethical theories, case study frameworks, and application-based learning — everything for a top Ethics score.",
    ],
    price: 149,
    originalPrice: 399,
    rating: null,
    reviewCount: null,
    badge: "13 Files",
    badgeColor: "amber",
    gradient: "bg-violet-600",
    features: [
      "13 comprehensive notes files",
      "Covers Ethics theory, case studies, human interface",
      "Notes from AIR 9, AIR 10, AIR 16, AIR 86, PRAHAAR",
      "Includes Lukman IAS and Gunjita notes",
      "Instant PDF download",
    ],
    category: "notes-bundle",
    payNote: "Ethics & GS 4 Bundle",
    payAmount: 149,
    link: null,
    comingSoon: false,
    image: "/images/products/ethics-gs4-bundle.png",
    fileCount: 13,
    totalSizeMB: 290,
    files: [
      { name: "AIR 10 MAINS NOTES GS 4.pdf", sizeMB: 2.9 },
      { name: "AZ GS4-1.pdf", sizeMB: 35.1 },
      { name: "Ethics AsadZuberi AIR 86.pdf", sizeMB: 68.3 },
      { name: "Ethics Notes AIR 9.pdf", sizeMB: 30.1 },
      { name: "EthicsTheory_Gunjita.pdf", sizeMB: 39.1 },
      { name: "Ethics_1.pdf", sizeMB: 8.0 },
      { name: "Ethics_2.pdf", sizeMB: 12.7 },
      { name: "Ethics_3.pdf", sizeMB: 11.3 },
      { name: "Ethics_and_Human_Interface.pdf", sizeMB: 0.1 },
      { name: "GS4_Ethics_Madhav_AIR16_CSE24_(with_Ratnesh).pdf", sizeMB: 12.7 },
      { name: "Lukman IAS Ethics Notes 2022 Part 1 (upscmaterial.online).pdf", sizeMB: 30.4 },
      { name: "Lukman IAS Ethics Notes 2022 Part 2 (upscmaterial.online).pdf", sizeMB: 20.5 },
    ],
  },
  {
    slug: "prelims-prep-pack",
    title: "Prelims Prep Pack",
      image: "/images/products/prelims-prep-pack.png",
    tagline: "10 files covering every Prelims subject",
    description: "Comprehensive Prelims preparation pack with Abhijit Ray's high-yield notes plus Ancient History, Environment, and World History.",
    longDescription: [
      "This pack combines Abhijit Ray's popular Prelims notes with additional high-value resources. 10 files covering Ancient History, Modern History, Polity, Geography, Environment, Science, Economics, and World History.",
      "Abhijit Ray's notes are known for their concise, exam-focused approach to Prelims subjects. Supplemented with Ancient History handwritten notes, Environment Short Notes, and World History.",
      "Everything you need for a thorough Prelims revision in one download.",
    ],
    price: 199,
    originalPrice: 499,
    rating: null,
    reviewCount: null,
    badge: "10 Files",
    badgeColor: "emerald",
    gradient: "bg-amber-600",
    features: [
      "10 files covering all Prelims subjects",
      "Abhijit Ray's high-yield subject notes (6 subjects)",
      "Ancient History handwritten notes + Environment Short Notes + World History",
      "Concise, exam-focused format",
      "Instant PDF download",
    ],
    category: "notes-bundle",
    payNote: "Prelims Prep Pack",
    payAmount: 199,
    link: null,
    comingSoon: false,
    image: "/images/products/prelims-prep-pack.png",
    fileCount: 10,
    totalSizeMB: 447,
    files: [
      { name: "ANCIENT HISTORY Handwritten Notes.pdf", sizeMB: 46.9 },
      { name: "Abhijit Ray economics high yeild supplementary notes.pdf", sizeMB: 6.3 },
      { name: "Abhijit Ray environment only pre supplementary notes.pdf", sizeMB: 23.5 },
      { name: "Abhijit Ray modern history pre and mains combined.pdf", sizeMB: 65.3 },
      { name: "Abhijit Ray polity supplementary notes for pre and mains.pdf", sizeMB: 33.8 },
      { name: "Abhijit Ray science supplementary notes only pre (1).pdf", sizeMB: 9.9 },
      { name: "Abhijit_Ray_geography_pre_only_high_yeild_supplementary_notes.pdf", sizeMB: 25.2 },
      { name: "ENVIRONMENT SHORT NOTES.pdf", sizeMB: 166.4 },
      { name: "Modern History_Prelims_ShortNotes.pdf", sizeMB: 44.7 },
      { name: "WorldHistory_Notes.pdf", sizeMB: 24.5 },
    ],
  },
  {
    slug: "polity-foundation",
    title: "Polity Foundation Notes",
      image: "/images/products/polity-foundation.png",
    tagline: "2 comprehensive files — complete Indian Polity coverage",
    description: "Detailed Polity Foundation notes covering every aspect of the Indian Constitution, system of government, and key institutions.",
    longDescription: [
      "Indian Polity is the backbone of both Prelims and Mains GS 2. These Foundation notes provide exhaustive coverage of every constitutional article, landmark judgment, and institutional framework.",
      "Two large files (265 MB total) with detailed, well-structured content. Ideal for building a solid Polity foundation from scratch.",
      "Covers: Historical background, Constitution features, Fundamental Rights, DPSP, Centre-State relations, Parliament, Judiciary, Governor, Constitutional bodies, and more.",
    ],
    price: 99,
    originalPrice: null,
    rating: null,
    reviewCount: null,
    badge: "2 Files",
    badgeColor: "amber",
    gradient: "bg-sky-700",
    features: [
      "2 files — 265 MB total",
      "Complete Indian Polity coverage",
      "Constitution, Parliament, Judiciary, Executive",
      "Landmark judgments and constitutional articles",
      "Instant PDF download",
    ],
    category: "notes-bundle",
    payNote: "Polity Foundation Notes",
    payAmount: 99,
    link: null,
    comingSoon: false,
    image: "/images/products/polity-foundation.png",
    fileCount: 2,
    totalSizeMB: 265,
    files: [
      { name: "Polity Foundation notes part 2.pdf", sizeMB: 139.8 },
      { name: "Polity foundation notes part 1.pdf", sizeMB: 124.8 },
    ],
  },
  {
    slug: "history-pack",
    title: "History Pack",
      image: "/images/products/history-pack.png",
    tagline: "4 files covering Ancient, Medieval, Modern & World History",
    description: "Complete history coverage for UPSC — Ancient, Medieval, Modern India, and World History in one pack.",
    longDescription: [
      "History is a high-scoring subject in both Prelims and Mains. This pack covers the entire spectrum from Ancient India through World History.",
      "Includes Ancient History handwritten notes, Art & Culture notes, Modern History notes, and World History notes.",
      "Perfect for aspirants who want a single comprehensive history resource instead of juggling multiple books.",
    ],
    price: 99,
    originalPrice: null,
    rating: null,
    reviewCount: null,
    badge: "4 Files",
    badgeColor: "amber",
    gradient: "bg-rose-700",
    features: [
      "4 files — 189 MB total",
      "Ancient, Medieval, Modern & World History",
      "Handwritten Ancient History notes included",
      "Art & Culture coverage",
      "Instant PDF download",
    ],
    category: "notes-bundle",
    payNote: "History Pack",
    payAmount: 99,
    link: null,
    comingSoon: false,
    image: "/images/products/history-pack.png",
    fileCount: 4,
    totalSizeMB: 189,
    files: [
      { name: "ANCIENT HISTORY Handwritten Notes.pdf", sizeMB: 46.9 },
      { name: "ArtCulture_Notes.pdf", sizeMB: 56.5 },
      { name: "ModernHistory_Notes.pdf", sizeMB: 61.6 },
      { name: "WorldHistory_Notes.pdf", sizeMB: 24.5 },
    ],
  },
  {
    slug: "air-10-mains-notes",
    title: "AIR 10 Mains Notes",
      image: "/images/products/air-10-mains-notes.png",
    tagline: "Complete GS Mains notes from AIR 10 — all 4 papers",
    description: "Handwritten and typed notes covering GS 1-4 from a top-10 rank holder. Essential for Mains answer writing approach.",
    longDescription: [
      "Full set of GS Mains notes (GS 1-4) prepared by an AIR 10 rank holder during their own UPSC preparation. These notes reveal how a top-10 ranker approached each paper.",
      "GS 1 covers Indian Heritage & Culture, History, Geography, and Society. GS 2 covers Polity, Governance, and Social Justice. GS 3 covers Economy, Agriculture, Environment, Science & Tech, and Security. GS 4 covers Ethics, Integrity, and Aptitude.",
      "A must-have reference to understand the depth and breadth expected at the highest scoring level.",
    ],
    price: 149,
    originalPrice: null,
    rating: null,
    reviewCount: null,
    badge: "4 Papers",
    badgeColor: "emerald",
    gradient: "bg-sky-600",
    features: [
      "4 files covering GS 1-4",
      "Complete Mains notes from AIR 10",
      "Reveals actual depth and structure of a top-10 ranker",
      "Typed and handwritten formats",
      "Instant PDF download",
    ],
    category: "teacher-brand",
    payNote: "AIR 10 Mains Notes",
    payAmount: 149,
    link: null,
    comingSoon: false,
    image: "/images/products/air-10-mains-notes.png",
    fileCount: 4,
    totalSizeMB: 179,
    files: [
      { name: "AIR 10 MAINS NOTES GS 1.pdf", sizeMB: 33.0 },
      { name: "AIR 10 MAINS NOTES GS 2.pdf", sizeMB: 76.0 },
      { name: "AIR 10 MAINS NOTES GS 3.pdf", sizeMB: 67.6 },
      { name: "AIR 10 MAINS NOTES GS 4.pdf", sizeMB: 2.9 },
    ],
  },
  {
    slug: "abhijit-ray-prelims-bundle",
    title: "Abhijit Ray Prelims Bundle",
      image: "/images/products/abhijit-ray-prelims-bundle.png",
    tagline: "6 high-yield subject notes for Prelims",
    description: "Abhijit Ray's curated prelims notes across 6 subjects.",
    longDescription: [
      "Abhijit Ray's Prelims notes are among the most recommended supplementary resources for UPSC Prelims. This bundle covers 6 subjects with high-yield, exam-focused content designed for quick revision.",
      "Subjects include: Ancient & Medieval India (Art & Culture), Modern India, Indian Polity, Indian Geography, Environment & Ecology, General Science, and Indian Economy.",
      "Each note is concise, point-wise, and focused on topics that appear frequently in Prelims.",
    ],
    price: 149,
    originalPrice: 399,
    rating: null,
    reviewCount: null,
    badge: "6 Subjects",
    badgeColor: "amber",
    gradient: "bg-indigo-600",
    features: [
      "6 high-yield Prelims subject notes by Abhijit Ray",
      "Covers Ancient/Medieval, Modern History, Polity, Geography, Environment, Science, Economics",
      "Point-wise, exam-focused content",
      "Ideal for quick revision and targeted prep",
      "Instant PDF download",
    ],
    category: "teacher-brand",
    payNote: "Abhijit Ray Prelims Bundle",
    payAmount: 149,
    link: null,
    comingSoon: false,
    image: "/images/products/abhijit-ray-prelims-bundle.png",
    fileCount: 6,
    totalSizeMB: 164,
    files: [
      { name: "Abhijit Ray economics high yeild supplementary notes.pdf", sizeMB: 6.3 },
      { name: "Abhijit Ray environment only pre supplementary notes.pdf", sizeMB: 23.5 },
      { name: "Abhijit Ray modern history pre and mains combined.pdf", sizeMB: 65.3 },
      { name: "Abhijit Ray polity supplementary notes for pre and mains.pdf", sizeMB: 33.8 },
      { name: "Abhijit Ray science supplementary notes only pre (1).pdf", sizeMB: 9.9 },
      { name: "Abhijit_Ray_geography_pre_only_high_yeild_supplementary_notes.pdf", sizeMB: 25.2 },
    ],
  },
  {
    slug: "environment-short-notes",
    title: "Environment Short Notes",
      image: "/images/products/environment-short-notes.png",
    tagline: "Concise environment notes for Prelims & Mains",
    description: "Comprehensive yet concise environment notes covering ecology, biodiversity, climate change, and environmental legislations.",
    longDescription: [
      "Environment & Ecology is one of the most scoring subjects in UPSC Prelims and carries significant weight in GS 3 Mains.",
      "Topics include: Ecology concepts, Indian biodiversity (national parks, wildlife sanctuaries, biosphere reserves), climate change & international conventions, environmental legislations, and current affairs.",
      "Designed for aspirants who want to cover the entire environment syllabus quickly without reading multiple bulky sources.",
    ],
    price: 99,
    originalPrice: null,
    rating: null,
    reviewCount: null,
    badge: "Bestseller",
    badgeColor: "amber",
    gradient: "bg-green-600",
    features: [
      "Complete environment syllabus coverage",
      "Ecology, biodiversity, climate change, legislations",
      "Concise, revision-friendly format",
      "Prelims and Mains focused",
      "Instant PDF download",
    ],
    category: "notes-bundle",
    payNote: "Environment Short Notes",
    payAmount: 99,
    link: null,
    comingSoon: false,
    image: "/images/products/environment-short-notes.png",
    fileCount: 1,
    totalSizeMB: 166,
    files: [
      { name: "ENVIRONMENT SHORT NOTES.pdf", sizeMB: 166.4 },
    ],
  },
  {
    slug: "mrunal-economy-complete",
    title: "Mrunal Economics Complete",
      image: "/images/products/mrunal-economy-complete.png",
    tagline: "Complete economics by Mrunal Patel",
    description: "Mrunal Patel's comprehensive economics notes covering Micro, Macro, Indian Economy, Budget & Economic Survey.",
    longDescription: [
      "Mrunal Patel is one of the most trusted names for UPSC Economics preparation. His notes cover the entire economics syllabus with clarity, data, and real-world examples.",
      "This 297 MB file is a complete economics reference covering Microeconomics, Macroeconomics, Indian Economy, Budget analysis, Economic Survey highlights, and more.",
      "Ideal for both Prelims (economics MCQs) and Mains (GS 3 economy questions).",
    ],
    price: 99,
    originalPrice: null,
    rating: null,
    reviewCount: null,
    badge: "1 File",
    badgeColor: "emerald",
    gradient: "bg-teal-600",
    features: [
      "Complete economics notes by Mrunal Patel (297 MB)",
      "Covers Micro, Macro, Indian Economy",
      "Budget & Economic Survey analysis",
      "Data-driven with real-world examples",
      "Instant PDF download",
    ],
    category: "teacher-brand",
    payNote: "Mrunal Economics Complete",
    payAmount: 99,
    link: null,
    comingSoon: false,
    image: "/images/products/mrunal-economy-complete.png",
    fileCount: 1,
    totalSizeMB: 297,
    files: [
      { name: "MRUNAL SIR SHORT NOTES.pdf", sizeMB: 296.5 },
    ],
  },
  {
    slug: "satyam-gandhi-mains-complete",
    title: "Satyam Gandhi Mains Complete",
      image: "/images/products/satyam-gandhi-mains-complete.png",
    tagline: "GS 1-3 Mains notes by Satyam Gandhi (AIR 82)",
    description: "Detailed GS Mains notes by Satyam Gandhi (AIR 82) covering GS 1, GS 2, and GS 3 with Essay insights.",
    longDescription: [
      "Satyam Gandhi (AIR 82, CSE 2023) is known for his structured and comprehensive Mains notes. This bundle includes his GS 1, GS 2, and GS 3 notes along with essay insights.",
      "GS 1 covers History, Geography, and Society. GS 2 covers Polity, Governance, and IR. GS 3 covers Economy, Environment, Science & Tech, and Security.",
      "At 314 MB across 3 files, these are some of the most detailed topper notes available.",
    ],
    price: 149,
    originalPrice: 399,
    rating: null,
    reviewCount: null,
    badge: "3 Files",
    badgeColor: "emerald",
    gradient: "bg-cyan-700",
    features: [
      "3 files — 314 MB total",
      "GS 1, 2, 3 notes by AIR 82",
      "Essay insights included",
      "Structured, comprehensive content",
      "Instant PDF download",
    ],
    category: "teacher-brand",
    payNote: "Satyam Gandhi Mains Complete",
    payAmount: 149,
    link: null,
    comingSoon: false,
    image: "/images/products/satyam-gandhi-mains-complete.png",
    fileCount: 3,
    totalSizeMB: 314,
    files: [
      { name: "GS-1 Notes_and_Essay_Satyam_Gandhi.pdf", sizeMB: 124.3 },
      { name: "GS-2 Notes_Satyam_Gandhi.pdf", sizeMB: 69.2 },
      { name: "GS-3 Notes_Satyam_Gandhi.pdf", sizeMB: 120.5 },
    ],
  },
  {
    slug: "asad-zuberi-air86-complete",
    title: "Asad Zuberi AIR 86 Complete",
      image: "/images/products/asad-zuberi-air86-complete.png",
    tagline: "Full notes package by Asad Zuberi (AIR 86)",
    description: "Complete GS 1-4, Ethics, and Geography notes from AIR 86 rank holder Asad Zuberi.",
    longDescription: [
      "Asad Zuberi (AIR 86) has created one of the most comprehensive topper note sets available. This bundle includes 12 files covering GS 1-4, Ethics (detailed), Geography (with diagrams), and evaluated answer copies.",
      "Includes: GS 1 (Art & Culture + Evaluated copy), GS 2 (detailed notes), GS 3 (two-part notes), GS 4 (Ethics + case studies), Geography diagrams, and evaluated answer sheets.",
      "A complete Mains preparation toolkit from a single topper who scored in the top 100.",
    ],
    price: 199,
    originalPrice: 499,
    rating: null,
    reviewCount: null,
    badge: "12 Files",
    badgeColor: "emerald",
    gradient: "bg-rose-700",
    features: [
      "12 files — 475 MB total",
      "GS 1-4 complete by AIR 86",
      "Ethics detailed notes included",
      "Geography diagrams included",
      "Instant PDF download",
    ],
    category: "teacher-brand",
    payNote: "Asad Zuberi AIR 86 Complete",
    payAmount: 199,
    link: null,
    comingSoon: false,
    image: "/images/products/asad-zuberi-air86-complete.png",
    fileCount: 12,
    totalSizeMB: 475,
    files: [
      { name: "A&C Asad Zuberi AIR86.pdf", sizeMB: 39.6 },
      { name: "AZ GS1 Evaluated.pdf", sizeMB: 38.5 },
      { name: "AZ GS1-1.pdf", sizeMB: 31.2 },
      { name: "AZ GS1-2.pdf", sizeMB: 25.9 },
      { name: "AZ GS2-1.pdf", sizeMB: 32.5 },
      { name: "AZ GS3-1.pdf", sizeMB: 32.6 },
      { name: "AZ GS3-2.pdf", sizeMB: 26.7 },
      { name: "AZ GS4-1.pdf", sizeMB: 35.1 },
      { name: "Ethics AsadZuberi AIR 86.pdf", sizeMB: 68.3 },
      { name: "GS2 AsadZuberi AIR86.pdf", sizeMB: 75.3 },
      { name: "GS3 AsadZuberiAIR 86.pdf", sizeMB: 60.4 },
      { name: "Geography Diagrams Asad Zuberi AIR86.pdf", sizeMB: 8.4 },
    ],
  },
  {
    slug: "madhav-air16-complete",
    title: "Madhav AIR 16 Complete",
      image: "/images/products/madhav-air16-complete.png",
    tagline: "Full GS 1-4 notes by Madhav (AIR 16)",
    description: "Complete GS 1-4 notes with committees compilation by Madhav (AIR 16, CSE 2024).",
    longDescription: [
      "Madhav's AIR 16 rank in CSE 2024 makes his notes among the most current and relevant. This bundle covers GS 1-4 with subject-wise detailed PDFs and a special Committees Compilation.",
      "Includes 17 files covering Art & Culture, Geography, Modern History, Post-Independence History, Society, Polity, Governance, IR, Social Justice, Economy, Agriculture, Environment, Disaster Management, Internal Security, Science & Tech, and Ethics.",
      "Plus the exclusive GS Committees Compilation 2025 — a must-have for GS 2 and GS 4 questions on committees and commissions.",
    ],
    price: 199,
    originalPrice: 499,
    rating: null,
    reviewCount: null,
    badge: "17 Files",
    badgeColor: "emerald",
    gradient: "bg-purple-700",
    features: [
      "17 files — 173 MB total",
      "GS 1-4 complete by AIR 16 (CSE 2024)",
      "Subject-wise detailed PDFs",
      "Exclusive Committees Compilation 2025",
      "Instant PDF download",
    ],
    category: "teacher-brand",
    payNote: "Madhav AIR 16 Complete",
    payAmount: 199,
    link: null,
    comingSoon: false,
    image: "/images/products/madhav-air16-complete.png",
    fileCount: 17,
    totalSizeMB: 173,
    files: [
      { name: "GS1_Art_&_Culture_Madhav_AIR16_CSE24_(with_Ratnesh).pdf", sizeMB: 34.7 },
      { name: "GS1_Geography_Madhav_AIR16_CSE24_(with_Ratnesh).pdf", sizeMB: 24.0 },
      { name: "GS1_Modern_Indian_History_Madhav_AIR16_CSE24_(with_Ratnesh).pdf", sizeMB: 5.4 },
      { name: "GS1_Post_Independence_History_Madhav_AIR16_CSE24_with_Ratnesh.pdf", sizeMB: 3.8 },
      { name: "GS1_Society_Madhav_AIR16_CSE24_(with_Ratnesh).pdf", sizeMB: 2.9 },
      { name: "GS2_Governance_Madhav_AIR16_CSE24_(with_Ratnesh).pdf", sizeMB: 7.4 },
      { name: "GS2_International_Relations_Madhav_AIR16_CSE24_with_Ratnesh.pdf", sizeMB: 6.1 },
      { name: "GS2_Polity_&_Constitution_Madhav_AIR16_CSE24_with_Ratnesh.pdf", sizeMB: 12.6 },
      { name: "GS2_Social_Justice_Madhav_AIR16_CSE24_(with_Ratnesh).pdf", sizeMB: 3.7 },
      { name: "GS3_Agriculture_Madhav_AIR16_CSE24_(with_Ratnesh).pdf", sizeMB: 10.3 },
      { name: "GS3_Disaster_Management_Madhav_AIR16_CSE24_(with_Ratnesh).pdf", sizeMB: 11.8 },
      { name: "GS3_Economic_Development_Madhav_AIR16_CSE24_(with_Ratnesh).pdf", sizeMB: 13.2 },
    ],
  },
  {
    slug: "prahaar-complete",
    title: "PRAHAAR Complete",
      image: "/images/products/prahaar-complete.png",
    tagline: "GS 1-4 complete notes by PRAHAAR",
    description: "Comprehensive GS notes series by PRAHAAR covering all 4 Mains papers with 15 detailed files.",
    longDescription: [
      "PRAHAAR is known for producing structured, syllabus-complete notes that are popular among serious UPSC aspirants. This bundle includes 15 files covering every GS paper.",
      "GS 1: Art & Culture, Modern India, Post-Independence India, Indian Society, World History. GS 2: Polity, Governance, IR, Social Justice. GS 3: Economy, Environment, Geography & DM, Internal Security, S&T. GS 4: Ethics.",
      "A comprehensive single-source solution for Mains GS preparation.",
    ],
    price: 199,
    originalPrice: 499,
    rating: null,
    reviewCount: null,
    badge: "15 Files",
    badgeColor: "emerald",
    gradient: "bg-orange-700",
    features: [
      "15 files — 328 MB total",
      "GS 1-4 complete by PRAHAAR",
      "15 detailed subject-wise PDFs",
      "Structured, syllabus-complete format",
      "Instant PDF download",
    ],
    category: "teacher-brand",
    payNote: "PRAHAAR Complete",
    payAmount: 199,
    link: null,
    comingSoon: false,
    image: "/images/products/prahaar-complete.png",
    fileCount: 15,
    totalSizeMB: 328,
    files: [
      { name: "PRAHAAR_Art and Culture.pdf", sizeMB: 24.3 },
      { name: "PRAHAAR_Economy.pdf", sizeMB: 27.3 },
      { name: "PRAHAAR_Environment & Ecology.pdf", sizeMB: 29.5 },
      { name: "PRAHAAR_Ethics, Integrity and Aptitude.pdf", sizeMB: 18.6 },
      { name: "PRAHAAR_Geography and Disaster Management.pdf", sizeMB: 26.1 },
      { name: "PRAHAAR_Governance.pdf", sizeMB: 19.0 },
      { name: "PRAHAAR_Indian Polity and Constitution.pdf", sizeMB: 25.6 },
      { name: "PRAHAAR_Indian Society.pdf", sizeMB: 9.6 },
      { name: "PRAHAAR_Internal Security.pdf", sizeMB: 27.6 },
      { name: "PRAHAAR_International Relations.pdf", sizeMB: 22.4 },
      { name: "PRAHAAR_Modern India.pdf", sizeMB: 20.4 },
      { name: "PRAHAAR_Post-Independece India.pdf", sizeMB: 16.6 },
    ],
  },
  {
    slug: "antriksh-gs-notes",
    title: "Antriksh GS Notes",
      image: "/images/products/antriksh-gs-notes.png",
    tagline: "5 focused GS notes by Antriksh",
    description: "Targeted GS notes by Antriksh covering Modern History, Geography, Governance, IR, and Disaster Management.",
    longDescription: [
      "Antriksh's notes are known for their focused, exam-oriented approach. This bundle includes 5 files covering the most important GS topics.",
      "Includes: Modern History, Geography (with maps), Governance, International Relations, and Disaster Management.",
      "Perfect for aspirants who want concise, targeted notes for specific GS topics without the fluff.",
    ],
    price: 149,
    originalPrice: 349,
    rating: null,
    reviewCount: null,
    badge: "5 Files",
    badgeColor: "amber",
    gradient: "bg-lime-700",
    features: [
      "5 files — 251 MB total",
      "Modern History, Geography, Governance, IR, DM",
      "Focused, exam-oriented approach",
      "Map-based geography coverage",
      "Instant PDF download",
    ],
    category: "teacher-brand",
    payNote: "Antriksh GS Notes",
    payAmount: 149,
    link: null,
    comingSoon: false,
    image: "/images/products/antriksh-gs-notes.png",
    fileCount: 5,
    totalSizeMB: 251,
    files: [
      { name: "Modern history antriksh-compressed.pdf", sizeMB: 34.4 },
      { name: "disaster management notes antriksh.pdf", sizeMB: 24.7 },
      { name: "geography notes antriksh (1)-compressed.pdf", sizeMB: 71.9 },
      { name: "governance notes antriksh.pdf", sizeMB: 44.0 },
      { name: "international relations (IR) Notes antriksh (1).pdf", sizeMB: 75.6 },
    ],
  },
  {
    slug: "dr-shivin-geography",
    title: "Dr. Shivin's Geography",
      image: "/images/products/dr-shivin-geography.png",
    tagline: "Complete Geography notes by Dr. Shivin",
    description: "Extensive geography reference covering Physical, Human, and Indian Geography by Dr. Shivin.",
    longDescription: [
      "Dr. Shivin's Geography notes are among the most comprehensive for UPSC optional and GS preparation. This single 152 MB file covers the entire geography syllabus.",
      "Includes: Physical Geography (geomorphology, climatology, oceanography), Human Geography, Indian Geography (regional planning, economic geography), and map-based questions.",
      "Ideal for Geography optional students and GS 1 geography preparation.",
    ],
    price: 99,
    originalPrice: null,
    rating: null,
    reviewCount: null,
    badge: "1 File",
    badgeColor: "amber",
    gradient: "bg-emerald-800",
    features: [
      "Complete geography notes by Dr. Shivin (152 MB)",
      "Physical, Human & Indian Geography covered",
      "Map-based question preparation",
      "Ideal for optional and GS 1",
      "Instant PDF download",
    ],
    category: "teacher-brand",
    payNote: "Dr. Shivin's Geography",
    payAmount: 99,
    link: null,
    comingSoon: false,
    image: "/images/products/dr-shivin-geography.png",
    fileCount: 1,
    totalSizeMB: 152,
    files: [
      { name: "Complete Geography Notes by Dr. Shivin .pdf", sizeMB: 152.5 },
    ],
  },
  {
    slug: "anthropology-bundle",
    title: "Anthropology Optional Bundle",
      image: "/images/products/anthropology-bundle.png",
    tagline: "14 files — complete Anthropology coverage by Laghima Tiwari (AIR 176) & Dr. Apala Mishra (AIR 9)",
    description: "Comprehensive Anthropology optional notes with test papers by rank holders.",
    longDescription: [
      "Anthropology is one of the most popular UPSC optionals with high scoring potential. This bundle covers both Paper 1 and Paper 2.",
      "Includes detailed notes by Laghima Tiwari (AIR 176) — 6 theory PDFs covering the entire syllabus. Plus Dr. Apala Mishra (AIR 9) — 4 anthropology PDFs. And 6 test papers for practice.",
      "Everything you need for a top Anthropology score in one bundle.",
    ],
    price: 299,
    originalPrice: 599,
    rating: null,
    reviewCount: null,
    badge: "14 Files",
    badgeColor: "emerald",
    gradient: "bg-amber-800",
    features: [
      "14 files — 548 MB total",
      "Paper 1 & Paper 2 complete coverage",
      "Notes by Laghima Tiwari (AIR 176) & Dr. Apala Mishra (AIR 9)",
      "6 test papers for practice included",
      "Instant PDF download",
    ],
    category: "optional",
    payNote: "Anthropology Optional Bundle",
    payAmount: 299,
    link: null,
    comingSoon: false,
    image: "/images/products/anthropology-bundle.png",
    fileCount: 14,
    totalSizeMB: 548,
    files: [
      { name: "Anthropology 1 - Laghima Tiwari.pdf", sizeMB: 81.1 },
      { name: "Anthropology 2 - Laghima Tiwari.pdf", sizeMB: 71.4 },
      { name: "Anthropology 3 - Laghima Tiwari.pdf", sizeMB: 139.0 },
      { name: "Anthropology 4 - Laghima Tiwari.pdf", sizeMB: 66.4 },
      { name: "DR_APALA_MISHRA_RANK_9_CSE_2020_ANTHROINDIAN.pdf", sizeMB: 22.1 },
      { name: "DR_APALA_MISHRA_RANK_9_CSE_2020_ANTHROPHYSICAL.pdf", sizeMB: 21.6 },
      { name: "DR_APALA_MISHRA_RANK_9_CSE_2020_ANTHROSOCIAL.pdf", sizeMB: 27.8 },
      { name: "DR_APALA_MISHRA_RANK_9_CSE_2020_ANTHROTRIBAL.pdf", sizeMB: 12.5 },
      { name: "Laghima Tiwari  test 4 anthro.pdf", sizeMB: 22.3 },
      { name: "Laghima Tiwari test 2 Anthro.pdf", sizeMB: 15.2 },
      { name: "Laghima Tiwari test 3 anthro.pdf", sizeMB: 18.7 },
      { name: "Laghima Tiwari test 5 anthro.pdf", sizeMB: 14.5 },
    ],
  },
  {
    slug: "geography-bundle",
    title: "Geography Optional Bundle",
      image: "/images/products/geography-bundle.png",
    tagline: "4 files covering Physical, Human & Indian Geography",
    description: "Complete Geography optional notes from Dr. Shivin, Asad Zuberi (AIR 86), and Rushikesh.",
    longDescription: [
      "Geography is a high-scoring optional with significant overlap with GS. This bundle brings together the best geography resources from multiple sources.",
      "Includes: Dr. Shivin's Complete Geography (152 MB), Asad Zuberi's Geography Diagrams, Rushikesh's Geography notes, and Rushikesh's Indian Geography handwritten notes.",
      "Comprehensive coverage for both optional and GS geography preparation.",
    ],
    price: 199,
    originalPrice: 449,
    rating: null,
    reviewCount: null,
    badge: "4 Files",
    badgeColor: "emerald",
    gradient: "bg-green-800",
    features: [
      "4 files — 237 MB total",
      "Dr. Shivin's Complete Geography",
      "Asad Zuberi Geography Diagrams (AIR 86)",
      "Rushikesh's Indian Geography handwritten notes",
      "Instant PDF download",
    ],
    category: "optional",
    payNote: "Geography Optional Bundle",
    payAmount: 199,
    link: null,
    comingSoon: false,
    image: "/images/products/geography-bundle.png",
    fileCount: 4,
    totalSizeMB: 237,
    files: [
      { name: "Complete Geography Notes by Dr. Shivin .pdf", sizeMB: 152.5 },
      { name: "Geography Diagrams Asad Zuberi AIR86.pdf", sizeMB: 8.4 },
      { name: "Geography_Rushikesh_notes.pdf", sizeMB: 49.4 },
      { name: "Rushikesh_Dudhat_Indian_Geography_Hand_Written_Notes_PDF_upscpdf.pdf", sizeMB: 26.5 },
    ],
  },
  {
    slug: "vp-2026-test-series",
    title: "VP 2026 Test Series",
      image: "/images/products/vp-2026-test-series.png",
    tagline: "20 bilingual Mains tests covering GS 1-4",
    description: "Full-length Mains test series by VP 2026 — 20 tests with bilingual (English + Hindi) question papers.",
    longDescription: [
      "VP 2026 Test Series is a comprehensive Mains answer writing practice resource. 20 full-length tests covering GS Papers 1-4 with bilingual question papers.",
      "Each test follows the actual UPSC Mains pattern with a mix of conceptual, analytical, and application-based questions.",
      "Includes both English and Hindi versions, making it ideal for Hindi medium aspirants.",
    ],
    price: 149,
    originalPrice: 349,
    rating: null,
    reviewCount: null,
    badge: "20 Tests",
    badgeColor: "emerald",
    gradient: "bg-blue-800",
    features: [
      "20 bilingual Mains tests (67 MB)",
      "GS 1-4 full-length coverage",
      "English + Hindi versions",
      "UPSC Mains pattern questions",
      "Instant PDF download",
    ],
    category: "test-series",
    payNote: "VP 2026 Test Series",
    payAmount: 149,
    link: null,
    comingSoon: false,
    image: "/images/products/vp-2026-test-series.png",
    fileCount: 20,
    totalSizeMB: 67,
    files: [
      { name: "VP 2026 TEST 11 ENG (upsccopycenter.com).pdf", sizeMB: 1.6 },
      { name: "VP 2026 TEST 11 Hindi (upsccopycenter.com).pdf", sizeMB: 1.4 },
      { name: "VP 2026 TEST 12 ENG (upsccopycenter.com).pdf", sizeMB: 7.3 },
      { name: "VP 2026 TEST 12 Hindi (upsccopycenter.com).pdf", sizeMB: 2.0 },
      { name: "VP 2026 TEST 13 ENG (upsccopycenter.com).pdf", sizeMB: 1.1 },
      { name: "VP 2026 TEST 13 Hindi (upsccopycenter.com).pdf", sizeMB: 1.1 },
      { name: "VP 2026 TEST 14 ENG (upsccopycenter.com).pdf", sizeMB: 1.2 },
      { name: "VP 2026 TEST 14 Hindi (upsccopycenter.com).pdf", sizeMB: 2.9 },
      { name: "VP 2026 TEST 15 ENG (upsccopycenter.com).pdf", sizeMB: 1.2 },
      { name: "VP 2026 TEST 15 Hindi (upsccopycenter.com).pdf", sizeMB: 2.9 },
      { name: "VP 2026 TEST 16 ENG (upsccopycenter.com).pdf", sizeMB: 7.2 },
      { name: "VP 2026 TEST 16 Hindi (upsccopycenter.com).pdf", sizeMB: 4.6 },
    ],
  },
  {
    slug: "visionias-test-series",
    title: "VisionIAS Test Series",
      image: "/images/products/visionias-test-series.png",
    tagline: "24 tests — FLTs, Socio tests, PTS & Rishabh Guidance",
    description: "Comprehensive Mains test series by VisionIAS including Socio FLTs, Rishabh Guidance, and PTS.",
    longDescription: [
      "VisionIAS is one of India's premier UPSC coaching institutes. This bundle includes 24 diverse test papers covering GS 1-4, CSAT, and Socio FLTs.",
      "Includes: PTS GS FLTs, PTS CSAT FLT, Rishabh Guidance tests (Comprehensive + Modular), Recognition IAS tests, Socio FLTs by Saurabh Sharma.",
      "The Rishabh Guidance tests are especially valuable — they target specific socio-economic themes with model answers.",
    ],
    price: 149,
    originalPrice: 399,
    rating: null,
    reviewCount: null,
    badge: "24 Tests",
    badgeColor: "emerald",
    gradient: "bg-sky-800",
    features: [
      "24 diverse test papers (306 MB)",
      "PTS FLTs, Socio FLTs, Rishabh Guidance",
      "GS 1-4 + CSAT coverage",
      "Includes Summary of Vision FLTs",
      "Instant PDF download",
    ],
    category: "test-series",
    payNote: "VisionIAS Test Series",
    payAmount: 149,
    link: null,
    comingSoon: false,
    image: "/images/products/visionias-test-series.png",
    fileCount: 24,
    totalSizeMB: 306,
    files: [
      { name: "2025_PTS_CSAT_FLT_01_TextBooklet.pdf", sizeMB: 2.3 },
      { name: "2025_PTS_GS_FLT_01_Answerkey.pdf", sizeMB: 0.3 },
      { name: "2025_PTS_GS_FLT_01_Answers_Explanations-2.pdf", sizeMB: 4.0 },
      { name: "2025_PTS_GS_FLT_01_TextBooklet.pdf", sizeMB: 2.3 },
      { name: "PTS24_T36_GS_FLT1_Test_Questions_OMR_Answers_Explanations_English.pdf", sizeMB: 9.3 },
      { name: "Rishabh_Guidance Comprehensive Test Paper-1.pdf", sizeMB: 20.6 },
      { name: "Rishabh_Guidance Comprehensive Test Paper-2.pdf", sizeMB: 19.7 },
      { name: "Rishabh_Guidance Modular Test 1.pdf", sizeMB: 25.4 },
      { name: "Rishabh_Guidance Modular Test 2.pdf", sizeMB: 19.7 },
      { name: "Rishabh_Guidance Modular Test 3.pdf", sizeMB: 17.7 },
      { name: "Rishabh_Guidance Modular Test 4.pdf", sizeMB: 21.5 },
      { name: "Rishabh_Guidance Modular Test 5.pdf", sizeMB: 22.1 },
    ],
  },
  {
    slug: "only-ias-test-series",
    title: "Only IAS Test Series",
      image: "/images/products/only-ias-test-series.png",
    tagline: "14 Prelims tests by Only IAS",
    description: "Comprehensive Prelims test series by Only IAS — 14 full-length and AIOMT papers.",
    longDescription: [
      "Only IAS is known for its high-quality test series that simulate the actual UPSC Prelims experience. This bundle includes 14 tests.",
      "Includes: 10 PT tests (Tests 1-10) and 4 AIOMT papers (Mock 1-4) with current affairs focus.",
      "Detailed answer keys with explanations for every question to help you identify weak areas.",
    ],
    price: 149,
    originalPrice: 349,
    rating: null,
    reviewCount: null,
    badge: "14 Tests",
    badgeColor: "emerald",
    gradient: "bg-orange-700",
    features: [
      "14 Prelims test papers (37 MB)",
      "10 PT tests + 4 AIOMT papers",
      "Covers full GS Prelims syllabus",
      "Detailed answer keys and explanations",
      "Instant PDF download",
    ],
    category: "test-series",
    payNote: "Only IAS Test Series",
    payAmount: 149,
    link: null,
    comingSoon: false,
    image: "/images/products/only-ias-test-series.png",
    fileCount: 14,
    totalSizeMB: 37,
    files: [
      { name: "BINDER_AIOMT_MOCK-4_Current Affairs-1.pdf", sizeMB: 5.6 },
      { name: "BINDER_AIOMT_PAPER-1_MOCK-1.pdf", sizeMB: 5.3 },
      { name: "BINDER_AIOMT_PAPER-1_MOCK-3.pdf", sizeMB: 5.4 },
      { name: "BINDER_AIOMT_PAPER-2_MOCK-2.pdf", sizeMB: 2.5 },
      { name: "ONLY IAS PT TEST-1 (delhiupscmaterial.in).pdf", sizeMB: 3.1 },
      { name: "ONLY IAS PT TEST-10 (delhiupscmaterial.in).pdf", sizeMB: 1.3 },
      { name: "ONLY IAS PT TEST-2 (delhiupscmaterial.in).pdf", sizeMB: 2.7 },
      { name: "ONLY IAS PT TEST-3 (delhiupscmaterial.in).pdf", sizeMB: 1.2 },
      { name: "ONLY IAS PT TEST-4 (delhiupscmaterial.in).pdf", sizeMB: 3.1 },
      { name: "ONLY IAS PT TEST-5 (delhiupscmaterial.in).pdf", sizeMB: 1.1 },
      { name: "ONLY IAS PT TEST-6 (delhiupscmaterial.in).pdf", sizeMB: 1.6 },
      { name: "ONLY IAS PT TEST-7 (delhiupscmaterial.in).pdf", sizeMB: 1.6 },
    ],
  },
  {
    slug: "csk-csat-complete",
    title: "CSK's CSAT Micro Tests 1-26",
      image: "/images/products/csk-csat-complete.png",
    tagline: "26 topic-wise CSAT micro tests",
    description: "Complete CSAT practice with 26 topic-wise micro tests covering comprehension, reasoning, maths, and data interpretation.",
    longDescription: [
      "CSK's CSAT Micro Tests are designed to help you master the CSAT paper through focused topic-wise practice. 26 tests covering every CSAT topic in detail.",
      "Topics include: Reading Comprehension, Logical Reasoning, Quantitative Aptitude, Data Interpretation, and Verbal Ability.",
      "Each test comes with detailed solutions and time-management tips. Ideal for building speed and accuracy.",
    ],
    price: 149,
    originalPrice: 399,
    rating: null,
    reviewCount: null,
    badge: "26 Tests",
    badgeColor: "emerald",
    gradient: "bg-purple-700",
    features: [
      "26 topic-wise CSAT micro tests (42 MB)",
      "Covers comprehension, reasoning, maths, DI",
      "Detailed solutions for every question",
      "Focus on speed and accuracy building",
      "Instant PDF download",
    ],
    category: "test-series",
    payNote: "CSK CSAT Micro Tests Complete",
    payAmount: 149,
    link: null,
    comingSoon: false,
    image: "/images/products/csk-csat-complete.png",
    fileCount: 26,
    totalSizeMB: 42,
    files: [
      { name: "CSAT_MICRO_TEST 10_CSK'S CSAT OFFICIAL 2026.pdf", sizeMB: 1.7 },
      { name: "CSAT_MICRO_TEST 11_CSK'S CSAT OFFICIAL 2026.pdf", sizeMB: 1.9 },
      { name: "CSAT_MICRO_TEST 12_CSK'S CSAT OFFICIAL 2026.pdf", sizeMB: 1.9 },
      { name: "CSAT_MICRO_TEST 13_CSK'S CSAT OFFICIAL 2026.pdf", sizeMB: 1.3 },
      { name: "CSAT_MICRO_TEST 14_CSK'S CSAT OFFICIAL 2026.pdf", sizeMB: 1.5 },
      { name: "CSAT_MICRO_TEST 15_CSK'S CSAT OFFICIAL 2026.pdf", sizeMB: 1.7 },
      { name: "CSAT_MICRO_TEST 16_CSK'S CSAT OFFICIAL 2026.pdf", sizeMB: 1.6 },
      { name: "CSAT_MICRO_TEST 17_CSK'S CSAT OFFICIAL 2026.pdf", sizeMB: 1.3 },
      { name: "CSAT_MICRO_TEST 18_CSK'S CSAT OFFICIAL 2026.pdf", sizeMB: 1.7 },
      { name: "CSAT_MICRO_TEST 19_CSK'S CSAT OFFICIAL 2026.pdf", sizeMB: 2.5 },
      { name: "CSAT_MICRO_TEST 1_CSK'S CSAT OFFICIAL 2026.pdf", sizeMB: 1.5 },
      { name: "CSAT_MICRO_TEST 20_CSK'S CSAT OFFICIAL 2026.pdf", sizeMB: 2.2 },
    ],
  },
  {
    slug: "ias-baba-test-series",
    title: "IAS BABA Test Series",
      image: "/images/products/ias-baba-test-series.png",
    tagline: "8 tests — AIOMT (Prelims) + Mains tests",
    description: "Complete IAS BABA test series with 3 AIOMT Prelims + 5 Mains tests.",
    longDescription: [
      "IAS BABA is one of the most trusted names for UPSC test series. This bundle includes all their available tests.",
      "Includes: 3 All India Open Mock Tests (Prelims) and 5 Mains test papers covering GS 1-4.",
      "Ideal for aspirants who want IAS BABA's complete test series in one place.",
    ],
    price: 149,
    originalPrice: 349,
    rating: null,
    reviewCount: null,
    badge: "8 Tests",
    badgeColor: "emerald",
    gradient: "bg-emerald-700",
    features: [
      "8 test papers (18 MB)",
      "3 AIOMT Prelims + 5 Mains tests",
      "GS 1-4 full coverage",
      "Detailed answer keys",
      "Instant PDF download",
    ],
    category: "test-series",
    payNote: "IAS BABA Test Series",
    payAmount: 149,
    link: null,
    comingSoon: false,
    image: "/images/products/ias-baba-test-series.png",
    fileCount: 8,
    totalSizeMB: 18,
    files: [
      { name: "IAS BABA AIOMT-1 (delhiupscmaterial.in).pdf", sizeMB: 3.7 },
      { name: "IAS BABA AIOMT-2 (delhiupscmaterial.in).pdf", sizeMB: 3.0 },
      { name: "IAS BABA AIOMT-3 (delhiupscmaterial.in).pdf", sizeMB: 5.2 },
      { name: "IAS BABA MAINS T1 (2026) upsccopycenter.com.pdf", sizeMB: 1.0 },
      { name: "IAS BABA MAINS T2 (2026) upsccopycenter.com.pdf", sizeMB: 1.0 },
      { name: "IAS BABA MAINS T3 (2026) upsccopycenter.com.pdf", sizeMB: 1.4 },
      { name: "IAS BABA MAINS T4 (2026) upsccopycenter.com.pdf", sizeMB: 1.2 },
      { name: "IAS BABA MAINS T5 (2026) upsccopycenter.com.pdf", sizeMB: 1.4 },
    ],
  },
  {
    slug: "dhyeya-ias-prelims-tests",
    title: "Dhyeya IAS Prelims Tests",
      image: "/images/products/dhyeya-ias-prelims-tests.png",
    tagline: "4 full-length Prelims tests by Dhyeya IAS",
    description: "Full-length Prelims test papers by Dhyeya IAS with detailed answer keys.",
    longDescription: [
      "Dhyeya IAS is a well-known UPSC coaching institute with a track record of producing rank holders. This set includes 4 full-length Prelims test papers.",
      "Each test follows the actual UPSC Prelims pattern with 100 questions covering the complete GS syllabus.",
      "Detailed solutions help you understand the reasoning behind each answer.",
    ],
    price: 99,
    originalPrice: 249,
    rating: null,
    reviewCount: null,
    badge: "4 Tests",
    badgeColor: "amber",
    gradient: "bg-red-700",
    features: [
      "4 full-length Prelims tests (76 MB)",
      "Covers complete GS Prelims syllabus",
      "UPSC pattern with 100 questions each",
      "Detailed answer keys",
      "Instant PDF download",
    ],
    category: "test-series",
    payNote: "Dhyeya IAS Prelims Tests",
    payAmount: 99,
    link: null,
    comingSoon: false,
    image: "/images/products/dhyeya-ias-prelims-tests.png",
    fileCount: 4,
    totalSizeMB: 76,
    files: [
      { name: "DHYEYA IAS PRELIMS 2026 T1 (delhiupscmaterial.in).pdf", sizeMB: 31.6 },
      { name: "DHYEYA IAS PRELIMS 2026 T2 (delhiupscmaterial.in).pdf", sizeMB: 13.5 },
      { name: "DHYEYA IAS PRELIMS 2026 T3 (delhiupscmaterial.in).pdf", sizeMB: 14.6 },
      { name: "DHYEYA IAS PRELIMS 2026 T4 (delhiupscmaterial.in).pdf", sizeMB: 16.2 },
    ],
  },
  {
    slug: "ipm-prelims-test-series",
    title: "IPM Prelims Test Series",
      image: "/images/products/ipm-prelims-test-series.png",
    tagline: "10 full-length Prelims tests by IPM",
    description: "Comprehensive Prelims test series by IPM — 10 tests covering the complete GS syllabus.",
    longDescription: [
      "IPM's Prelims test series is known for its high-quality questions that match the actual UPSC difficulty level. This bundle includes 10 full-length tests.",
      "Each test follows the UPSC Prelims pattern with 100 questions covering History, Geography, Polity, Economy, Science & Tech, Environment, and Current Affairs.",
      "Detailed answer keys with explanations for effective self-evaluation.",
    ],
    price: 99,
    originalPrice: 249,
    rating: null,
    reviewCount: null,
    badge: "10 Tests",
    badgeColor: "amber",
    gradient: "bg-teal-700",
    features: [
      "10 full-length Prelims tests (18 MB)",
      "Covers complete GS Prelims syllabus",
      "UPSC-standard difficulty level",
      "Detailed answer keys with explanations",
      "Instant PDF download",
    ],
    category: "test-series",
    payNote: "IPM Prelims Test Series",
    payAmount: 99,
    link: null,
    comingSoon: false,
    image: "/images/products/ipm-prelims-test-series.png",
    fileCount: 10,
    totalSizeMB: 18,
    files: [
      { name: "IPM 2026 - Prelims Test 01 (upsccopycenter.com).pdf", sizeMB: 1.7 },
      { name: "IPM 2026 - Prelims Test 02 (upsccopycenter.com).pdf", sizeMB: 1.8 },
      { name: "IPM 2026 - Prelims Test 03 (upsccopycenter.com).pdf", sizeMB: 1.8 },
      { name: "IPM 2026 - Prelims Test 04 (upsccopycenter.com).pdf", sizeMB: 1.9 },
      { name: "IPM 2026 - Prelims Test 05 (upsccopycenter.com).pdf", sizeMB: 1.9 },
      { name: "IPM 2026 - Prelims Test 06 (upsccopycenter.com).pdf", sizeMB: 1.8 },
      { name: "IPM 2026 - Prelims Test 07 (upsccopycenter.com).pdf", sizeMB: 1.7 },
      { name: "IPM 2026 - Prelims Test 08 (upsccopycenter.com).pdf", sizeMB: 1.8 },
      { name: "IPM 2026 - Prelims Test 09 (upsccopycenter.com).pdf", sizeMB: 1.7 },
      { name: "IPM 2026 - Prelims Test 10 (upsccopycenter.com).pdf", sizeMB: 1.7 },
    ],
  },
  {
    slug: "mains-test-series-combo",
    title: "Mains Test Series Combo",
      image: "/images/products/mains-test-series-combo.png",
    tagline: "66 tests from 4 top coaching brands at 40% off",
    description: "VP 2026 + VisionIAS + Only IAS + IAS BABA Mains tests bundled together. The ultimate Mains answer writing practice repository.",
    longDescription: [
      "This combo brings together Mains test papers from 4 of India's leading UPSC coaching brands at a fraction of their individual cost.",
      "Includes: VP 2026 Test Series (20 tests in English & Hindi), VisionIAS Test Series (24 tests), Only IAS Test Series (14 tests), and IAS BABA Mains Tests (8 tests).",
      "Each test follows the actual UPSC Mains pattern with model answers and marking schemes.",
    ],
    price: 299,
    originalPrice: 496,
    rating: null,
    reviewCount: null,
    badge: "66 Tests",
    badgeColor: "emerald",
    gradient: "bg-rose-600",
    features: [
      "66 Mains tests from VP, VisionIAS, Only IAS, IAS BABA",
      "GS 1-4 full-length and sectional tests",
      "Model answers and marking schemes",
      "Diverse question styles across 4 brands",
      "Instant PDF download",
    ],
    category: "test-series",
    payNote: "Mains Test Series Combo",
    payAmount: 299,
    link: null,
    comingSoon: false,
  },
];

export function getProductBySlug(slug: string): StoreProduct | undefined {
  return PRODUCTS.find((p) => p.slug === slug);
}

export function getProductsByInstitute(instituteSlug: string): StoreProduct[] {
  return PRODUCTS.filter((p) => p.institute === instituteSlug && !p.comingSoon);
}

export function getInstituteBySlug(slug: string): Institute | undefined {
  return INSTITUTES.find((i) => i.slug === slug);
}
