import mongoose from "mongoose";
import { readFileSync, writeFileSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));

const MONGODB_URI = process.env.MONGODB_URI;
const DB_NAME = process.env.DB_NAME;

if (!MONGODB_URI || !DB_NAME) {
  console.error("Missing MONGODB_URI or DB_NAME in env");
  process.exit(1);
}

const pdfSchema = new mongoose.Schema(
  {
    title: { type: String, required: true },
    slug: { type: String, required: true, unique: true },
    description: { type: String, default: "" },
    category: {
      type: String,
      enum: ["test-series", "notes", "books", "magazines", "current-affairs", "optional", "other"],
      required: true,
    },
    brand: { type: String, default: "" },
    author: { type: String, default: "" },
    imagekitUrl: { type: String, default: "" },
    fileSize: { type: String, default: "" },
    pageCount: { type: Number, default: 0 },
    year: { type: Number },
    language: { type: String, enum: ["en", "hi", "both"], default: "en" },
    tags: [{ type: String }],
    isFeatured: { type: Boolean, default: false },
    downloadCount: { type: Number, default: 0 },
  },
  { timestamps: true }
);

const PDFModel = mongoose.models.PDF || mongoose.model("PDF", pdfSchema);

const PDFs = [
  // ===== TEST SERIES =====
  {
    title: "Vision IAS Test Series 2026 — Complete Prelims & Mains",
    slug: "vision-ias-test-series-2026",
    description: "Complete Vision IAS 2026 test series for UPSC Prelims and Mains. Includes GS, CSAT, and optional subject papers with solutions.",
    category: "test-series",
    brand: "Vision IAS",
    year: 2026,
    language: "en",
    pageCount: 0,
    tags: ["vision ias", "test series", "prelims", "mains", "2026"],
  },
  {
    title: "Forum IAS Test Series 2026 — Prelims & Mains",
    slug: "forum-ias-test-series-2026",
    description: "Forum IAS 2026 test series for UPSC. Full-length prelims and mains tests with detailed solutions and performance analysis.",
    category: "test-series",
    brand: "Forum IAS",
    year: 2026,
    language: "en",
    tags: ["forum ias", "test series", "prelims", "mains", "2026"],
  },
  {
    title: "Insights IAS Test Series 2025 — Prelims & Mains",
    slug: "insights-ias-test-series-2025",
    description: "Insights IAS 2025 test series for UPSC. Comprehensive prelims and mains tests with answer key and solutions.",
    category: "test-series",
    brand: "Insights IAS",
    year: 2025,
    language: "en",
    tags: ["insights ias", "test series", "prelims", "mains", "2025"],
  },
  {
    title: "Shankar IAS Test Series 2025 — Prelims",
    slug: "shankar-ias-test-series-2025",
    description: "Shankar IAS 2025 prelims test series with focus on environment, biodiversity, and general studies MCQs.",
    category: "test-series",
    brand: "Shankar IAS",
    year: 2025,
    language: "en",
    tags: ["shankar ias", "test series", "prelims", "environment", "2025"],
  },
  {
    title: "Next IAS Test Series 2026 — Prelims & Mains",
    slug: "next-ias-test-series-2026",
    description: "Next IAS 2026 test series for UPSC. Prelims and mains tests with detailed solutions and performance tracking.",
    category: "test-series",
    brand: "Next IAS",
    year: 2026,
    language: "en",
    tags: ["next ias", "test series", "prelims", "mains", "2026"],
  },
  {
    title: "Raus IAS Test Series 2024 — Prelims & Mains",
    slug: "raus-ias-test-series-2024",
    description: "Raus IAS 2024 test series for UPSC. Full-length tests with detailed solutions and model answers.",
    category: "test-series",
    brand: "Raus IAS",
    year: 2024,
    language: "en",
    tags: ["raus ias", "test series", "prelims", "mains", "2024"],
  },
  {
    title: "Only IAS Test Series 2024 — Prelims & Mains",
    slug: "only-ias-test-series-2024",
    description: "Only IAS 2024 test series for UPSC. Prelims and mains tests with answer writing practice and evaluation.",
    category: "test-series",
    brand: "Only IAS",
    year: 2024,
    language: "en",
    tags: ["only ias", "test series", "prelims", "mains", "2024"],
  },
  {
    title: "KSG IAS Test Series 2025 — Prelims & Mains",
    slug: "ksg-ias-test-series-2025",
    description: "KSG IAS 2025 test series for UPSC. Comprehensive test papers covering entire UPSC syllabus.",
    category: "test-series",
    brand: "KSG IAS",
    year: 2025,
    language: "en",
    tags: ["ksg ias", "test series", "prelims", "mains", "2025"],
  },
  {
    title: "Sunya IAS Test Series 2025 — Prelims & Mains",
    slug: "sunya-ias-test-series-2025",
    description: "Sunya IAS 2025 test series for UPSC. Prelims and mains tests with current affairs integration.",
    category: "test-series",
    brand: "Sunya IAS",
    year: 2025,
    language: "en",
    tags: ["sunya ias", "test series", "prelims", "mains", "2025"],
  },
  {
    title: "GS Score Test Series 2024 — Prelims & Mains",
    slug: "gs-score-test-series-2024",
    description: "GS Score 2024 test series for UPSC. Focus on conceptual clarity and answer writing skills.",
    category: "test-series",
    brand: "GS Score",
    year: 2024,
    language: "en",
    tags: ["gs score", "test series", "prelims", "mains", "2024"],
  },
  {
    title: "Drishti IAS Prelims 2025 Test Series",
    slug: "drishti-ias-prelims-test-series-2025",
    description: "Drishti IAS 2025 prelims test series in Hindi and English. Subject-wise and full-length MCQs.",
    category: "test-series",
    brand: "Drishti IAS",
    year: 2025,
    language: "both",
    tags: ["drishti ias", "test series", "prelims", "hindi", "english", "2025"],
  },
  {
    title: "UPSC NCERT Test Series 2025 — English & Hindi",
    slug: "upsc-ncert-test-series-2025",
    description: "NCERT-based test series for UPSC covering all subjects from class 6 to 12. Both English and Hindi medium.",
    category: "test-series",
    brand: "NCERT",
    year: 2025,
    language: "both",
    tags: ["ncert", "test series", "prelims", "hindi", "english", "2025"],
  },
  {
    title: "VAJI UPSC PRE Test Series 2026",
    slug: "vaji-upsc-pre-test-series-2026",
    description: "VAJI prelims test series 2026 with subject-wise and full-length tests for UPSC CSE.",
    category: "test-series",
    brand: "VAJI RAM",
    year: 2026,
    language: "en",
    tags: ["vajiram", "test series", "prelims", "2026"],
  },
  {
    title: "PSIR Optional Test Series for UPSC",
    slug: "psir-optional-test-series-upsc",
    description: "PSIR optional subject test series for UPSC Mains. Political Science and International Relations paper 1 and 2.",
    category: "test-series",
    brand: "PSIR",
    year: 2025,
    language: "en",
    tags: ["psir", "optional", "test series", "mains", "political science"],
  },
  {
    title: "UPSC Maths Optional Test Series 2024",
    slug: "upsc-maths-optional-test-series-2024",
    description: "Mathematics optional test series for UPSC Mains. Covers all topics with detailed solutions.",
    category: "test-series",
    brand: "Mathematics",
    year: 2024,
    language: "en",
    tags: ["mathematics", "maths", "optional", "test series", "mains"],
  },
  {
    title: "Hindi Literature Optional UPSC Test Series",
    slug: "hindi-literature-optional-upsc-test-series",
    description: "Hindi literature optional test series for UPSC Mains. Covers all sections of Hindi sahitya.",
    category: "test-series",
    brand: "Hindi Literature",
    language: "hi",
    tags: ["hindi literature", "optional", "test series", "mains"],
  },
  {
    title: "UPPSC Test Series 2025 — Prelims & Mains",
    slug: "uppsc-test-series-2025",
    description: "UPPSC 2025 prelims and mains test series for Uttar Pradesh PCS examination.",
    category: "test-series",
    brand: "UPPSC",
    year: 2025,
    language: "both",
    tags: ["uppsc", "test series", "prelims", "mains", "uttar pradesh"],
  },
  {
    title: "UPPSC RO/ARO Test Series 2025",
    slug: "uppsc-ro-aro-test-series-2025",
    description: "UPPSC RO/ARO 2025 test series for Review Officer and Assistant Review Officer examination.",
    category: "test-series",
    brand: "UPPSC",
    year: 2025,
    language: "hi",
    tags: ["uppsc", "ro aro", "test series", "uttar pradesh"],
  },
  {
    title: "UPSC EPFO EO/AO/APFC Test Series",
    slug: "upsc-epfo-test-series",
    description: "UPSC EPFO Enforcement Officer/Accounts Officer test series. Complete coverage of EPFO syllabus.",
    category: "test-series",
    brand: "EPFO",
    language: "en",
    tags: ["epfo", "enforcement officer", "accounts officer", "apfc", "test series"],
  },
  {
    title: "IASBABA 2024 Test Series — Prelims & Mains",
    slug: "iasbaba-2024-test-series",
    description: "IASBABA 2024 test series for UPSC including ILP tests, prelims tests, and mains tests.",
    category: "test-series",
    brand: "IASBABA",
    year: 2024,
    language: "en",
    tags: ["iasbaba", "test series", "prelims", "mains", "2024"],
  },

  // ===== NOTES =====
  {
    title: "Forum IAS Ethics Handouts Notes PDF",
    slug: "forum-ias-ethics-handouts-notes",
    description: "Forum IAS comprehensive ethics handouts for UPSC Mains GS Paper 4. Covers all ethical theories, case studies, and moral thinkers.",
    category: "notes",
    brand: "Forum IAS",
    tags: ["forum ias", "ethics", "gs4", "handouts", "notes", "mains"],
    pageCount: 200,
  },
  {
    title: "Sriram IAS Economy Notes PDF for UPSC",
    slug: "sriram-ias-economy-notes",
    description: "Sriram IAS economy notes covering Indian economy for UPSC Prelims and Mains. Includes GDP, inflation, banking, budget, and economic surveys.",
    category: "notes",
    brand: "Sriram IAS",
    tags: ["sriram ias", "economy", "notes", "indian economy", "prelims", "mains"],
    pageCount: 150,
  },
  {
    title: "MK Yadav Sir Indian Society Notes PDF",
    slug: "mk-yadav-indian-society-notes",
    description: "MK Yadav sir's comprehensive Indian society notes for UPSC Mains. Covers social structure, diversity, urbanization, and social issues.",
    category: "notes",
    brand: "MK Yadav",
    author: "MK Yadav",
    tags: ["mk yadav", "indian society", "notes", "mains", "gs1"],
    pageCount: 120,
  },
  {
    title: "MK Yadav Sir Geography & Disaster Management Notes PDF",
    slug: "mk-yadav-geography-disaster-management-notes",
    description: "MK Yadav sir's geography and disaster management notes for UPSC Mains. Covers physical, human geography and disaster response.",
    category: "notes",
    brand: "MK Yadav",
    author: "MK Yadav",
    tags: ["mk yadav", "geography", "disaster management", "notes", "mains"],
    pageCount: 180,
  },
  {
    title: "MK Yadav Sir Environment & Ecology Notes PDF",
    slug: "mk-yadav-environment-ecology-notes",
    description: "MK Yadav sir's environment and ecology notes for UPSC. Covers biodiversity, climate change, conservation, and environmental policies.",
    category: "notes",
    brand: "MK Yadav",
    author: "MK Yadav",
    tags: ["mk yadav", "environment", "ecology", "notes", "prelims", "mains"],
    pageCount: 140,
  },
  {
    title: "Drishti IAS Notes 2025 — Free Books Hindi & English",
    slug: "drishti-ias-notes-2025",
    description: "Drishti IAS comprehensive notes for UPSC in Hindi and English. Subject-wise coverage for Prelims and Mains.",
    category: "notes",
    brand: "Drishti IAS",
    year: 2025,
    language: "both",
    tags: ["drishti ias", "notes", "hindi", "english", "prelims", "mains", "2025"],
    pageCount: 800,
  },
  {
    title: "Only IAS Prahaar 2025 Booklet PDF",
    slug: "only-ias-prahaar-2025-booklet",
    description: "Only IAS Prahaar 2025 booklet for UPSC Prelims. Rapid revision material with key facts, MCQs, and quick notes.",
    category: "notes",
    brand: "Only IAS",
    year: 2025,
    language: "en",
    tags: ["only ias", "prahaar", "booklet", "prelims", "revision", "2025"],
    pageCount: 300,
  },
  {
    title: "Only IAS Udaan PDF Free Download",
    slug: "only-ias-udaan-pdf",
    description: "Only IAS Udaan program PDF for UPSC. Foundation course material covering all GS subjects from basics.",
    category: "notes",
    brand: "Only IAS",
    language: "en",
    tags: ["only ias", "udaan", "foundation", "notes", "gs", "prelims"],
    pageCount: 500,
  },
  {
    title: "Shankar IAS Environment MCQ PDF",
    slug: "shankar-ias-environment-mcq",
    description: "Shankar IAS environment MCQ book for UPSC Prelims. Practice questions on ecology, biodiversity, climate change, and environmental policy.",
    category: "notes",
    brand: "Shankar IAS",
    tags: ["shankar ias", "environment", "mcq", "prelims", "practice"],
    pageCount: 200,
  },
  {
    title: "La Excellence RRP Mains Indian Society Notes PDF",
    slug: "la-excellence-rrp-indian-society-notes",
    description: "La Excellence RRP (Rapid Revision Program) Indian Society notes for UPSC Mains. Concise and exam-focused.",
    category: "notes",
    brand: "La Excellence",
    tags: ["la excellence", "rrp", "indian society", "notes", "mains", "revision"],
    pageCount: 80,
  },
  {
    title: "La Excellence RRP Mains Governance Notes PDF",
    slug: "la-excellence-rrp-governance-notes",
    description: "La Excellence RRP governance notes for UPSC Mains covering administrative reforms, e-governance, and public policy.",
    category: "notes",
    brand: "La Excellence",
    tags: ["la excellence", "rrp", "governance", "notes", "mains"],
    pageCount: 70,
  },
  {
    title: "La Excellence RRP Mains Polity Notes PDF",
    slug: "la-excellence-rrp-polity-notes",
    description: "La Excellence RRP polity notes for UPSC Mains covering constitution, parliament, judiciary, federalism, and constitutional bodies.",
    category: "notes",
    brand: "La Excellence",
    tags: ["la excellence", "rrp", "polity", "notes", "mains"],
    pageCount: 90,
  },
  {
    title: "PW Only IAS Mind Maps — Indian Polity",
    slug: "pw-only-ias-mind-maps-indian-polity",
    description: "PW Only IAS mind maps for Indian Polity. Visual summaries of constitution, governance, and political system for quick revision.",
    category: "notes",
    brand: "PW Only IAS",
    tags: ["pw only ias", "mind maps", "polity", "revision", "prelims", "mains"],
    pageCount: 60,
  },
  {
    title: "PW Only IAS Mind Maps — Indian Economy",
    slug: "pw-only-ias-mind-maps-economy",
    description: "PW Only IAS mind maps for Indian Economy. Visual summaries of economic concepts, policies, and budgets for UPSC.",
    category: "notes",
    brand: "PW Only IAS",
    tags: ["pw only ias", "mind maps", "economy", "revision", "prelims", "mains"],
    pageCount: 50,
  },
  {
    title: "Mahapatra Sir Sociology Notes PDF for UPSC",
    slug: "mahapatra-sir-sociology-notes-upsc",
    description: "Mahapatra sir's comprehensive sociology notes for UPSC optional. Covers sociological thinkers, theories, and Indian society.",
    category: "notes",
    brand: "Mahapatra Sir",
    author: "Mahapatra Sir",
    tags: ["mahapatra sir", "sociology", "optional", "notes", "mains"],
    pageCount: 350,
  },
  {
    title: "UPSC Notes PDF in Hindi",
    slug: "upsc-notes-pdf-hindi",
    description: "Comprehensive UPSC notes in Hindi covering all GS subjects for Prelims and Mains. Hindi medium study material.",
    category: "notes",
    brand: "General",
    language: "hi",
    tags: ["hindi", "notes", "upsc", "prelims", "mains", "gs"],
    pageCount: 600,
  },

  // ===== BOOKS =====
  {
    title: "Manorama Year Book 2026 PDF",
    slug: "manorama-year-book-2026",
    description: "Manorama Year Book 2026 — comprehensive reference book with current affairs, world events, country profiles, and general knowledge.",
    category: "books",
    brand: "Manorama",
    year: 2026,
    tags: ["manorama", "year book", "current affairs", "gk", "reference", "2026"],
    pageCount: 900,
  },
  {
    title: "PMF IAS Environment PDF — 2nd Edition",
    slug: "pmf-ias-environment-2nd-edition",
    description: "PMF IAS Environment book 2nd edition for UPSC. Complete coverage of ecology, biodiversity, climate change, and environmental policies.",
    category: "books",
    brand: "PMF IAS",
    tags: ["pmf ias", "environment", "book", "ecology", "prelims", "mains"],
    pageCount: 400,
  },
  {
    title: "Shankar IAS Environment 10th Edition PDF",
    slug: "shankar-ias-environment-10th-edition",
    description: "Shankar IAS Environment 10th edition — the most popular environment book for UPSC. Covers all topics with practice MCQs.",
    category: "books",
    brand: "Shankar IAS",
    tags: ["shankar ias", "environment", "book", "10th edition", "prelims"],
    pageCount: 350,
  },
  {
    title: "Dutt and Sundaram Indian Economy Book PDF",
    slug: "dutt-sundaram-indian-economy-book",
    description: "Dutt and Sundaram Indian Economy textbook. Comprehensive coverage of Indian economic development, policies, and planning.",
    category: "books",
    brand: "Dutt & Sundaram",
    tags: ["dutt sundaram", "indian economy", "book", "economics", "prelims", "mains"],
    pageCount: 700,
  },
  {
    title: "Fundamentals of Essay and Answer Writing Book for UPSC Mains",
    slug: "fundamentals-of-essay-answer-writing-book",
    description: "Comprehensive guide to essay and answer writing for UPSC Mains. Covers structure, frameworks, and practice exercises.",
    category: "books",
    brand: "Essay",
    tags: ["essay", "answer writing", "book", "mains", "writing skills"],
    pageCount: 300,
  },
  {
    title: "Anthropology Demystified by Akshat Jain IAS PDF",
    slug: "anthropology-demystified-akshat-jain",
    description: "Anthropology Demystified book by Akshat Jain IAS (AIR 27). Comprehensive optional subject guide with diagrams and case studies.",
    category: "books",
    brand: "Akshat Jain",
    author: "Akshat Jain",
    tags: ["anthropology", "optional", "akshat jain", "book", "mains"],
    pageCount: 500,
  },
  {
    title: "Oxford School Atlas 36th Edition PDF",
    slug: "oxford-school-atlas-36th-edition",
    description: "Oxford School Atlas 36th edition — essential for UPSC geography preparation. Maps, data, and geographical information.",
    category: "books",
    brand: "Oxford",
    tags: ["oxford", "atlas", "geography", "maps", "prelims", "mains"],
    pageCount: 200,
  },
  {
    title: "Arihant 151 Essays for UPSC Mains by SC Gupta",
    slug: "arihant-151-essays-upsc-mains-sc-gupta",
    description: "Arihant 151 Essays for UPSC Mains by SC Gupta. Covers diverse topics with structure, vocabulary, and sample essays.",
    category: "books",
    brand: "Arihant",
    author: "SC Gupta",
    tags: ["arihant", "essays", "upsc mains", "sc gupta", "essay writing"],
    pageCount: 400,
  },
  {
    title: "Haralambos and Holborn Sociology Book PDF",
    slug: "haralambos-holborn-sociology-book",
    description: "Haralambos and Holborn Sociology — standard textbook for sociology optional. Covers sociological theories and perspectives.",
    category: "books",
    brand: "Haralambos & Holborn",
    tags: ["haralambos", "holborn", "sociology", "optional", "book", "textbook"],
    pageCount: 800,
  },
  {
    title: "Ethics Integrity and Aptitude by G Subba Rao PDF",
    slug: "ethics-integrity-aptitude-g-subba-rao",
    description: "Ethics Integrity and Aptitude by G Subba Rao for UPSC Mains GS Paper 4. Comprehensive coverage with case studies.",
    category: "books",
    brand: "G Subba Rao",
    author: "G Subba Rao",
    tags: ["ethics", "integrity", "aptitude", "g subba rao", "gs4", "mains"],
    pageCount: 400,
  },
  {
    title: "Norman Lowe Mastering Modern World History PDF",
    slug: "mastering-modern-world-history-norman-lowe",
    description: "Mastering Modern World History by Norman Lowe — essential for UPSC world history preparation. Covers all major events.",
    category: "books",
    brand: "Norman Lowe",
    author: "Norman Lowe",
    tags: ["norman lowe", "world history", "modern history", "book", "prelims", "mains"],
    pageCount: 600,
  },
  {
    title: "The Answer Writing Manual by Srushti Deshmukh",
    slug: "answer-writing-manual-srushti-deshmukh",
    description: "Answer Writing Manual by Srushti Deshmukh (AIR 5). Proven techniques for structuring high-scoring UPSC Mains answers.",
    category: "books",
    brand: "Srushti Deshmukh",
    author: "Srushti Deshmukh",
    tags: ["srushti deshmukh", "answer writing", "manual", "mains", "strategy"],
    pageCount: 250,
  },

  // ===== MAGAZINES =====
  {
    title: "Yojana Magazine Monthly PDF — Free Download",
    slug: "yojana-magazine-monthly-pdf",
    description: "Yojana magazine monthly issues for UPSC. Government publication covering development topics, schemes, and policy analysis.",
    category: "magazines",
    brand: "Yojana",
    tags: ["yojana", "magazine", "monthly", "current affairs", "government"],
    pageCount: 100,
  },
  {
    title: "Kurukshetra Magazine Monthly PDF — Free Download",
    slug: "kurukshetra-magazine-monthly-pdf",
    description: "Kurukshetra magazine for UPSC. Focus on rural development, agriculture, and social issues.",
    category: "magazines",
    brand: "Kurukshetra",
    tags: ["kurukshetra", "magazine", "monthly", "rural development", "agriculture"],
    pageCount: 80,
  },
  {
    title: "Vision IAS Monthly Current Affairs Magazine PDF",
    slug: "vision-ias-monthly-current-affairs-magazine",
    description: "Vision IAS monthly current affairs magazine. Comprehensive coverage of important current events for UPSC.",
    category: "magazines",
    brand: "Vision IAS",
    tags: ["vision ias", "monthly", "current affairs", "magazine", "prelims", "mains"],
    pageCount: 150,
  },
  {
    title: "Insights Prime Magazine PDF for UPSC",
    slug: "insights-prime-magazine-pdf",
    description: "Insights Prime monthly magazine for UPSC current affairs. In-depth analysis of important topics.",
    category: "magazines",
    brand: "Insights IAS",
    tags: ["insights", "prime", "magazine", "current affairs", "monthly"],
    pageCount: 120,
  },
  {
    title: "Raus IAS Focus Magazine PDF",
    slug: "raus-ias-focus-magazine-pdf",
    description: "Raus IAS Focus monthly magazine for UPSC current affairs preparation.",
    category: "magazines",
    brand: "Raus IAS",
    tags: ["raus ias", "focus", "magazine", "current affairs", "monthly"],
    pageCount: 100,
  },
  {
    title: "Pratiyogita Darpan Magazine PDF",
    slug: "pratiyogita-darpan-magazine-pdf",
    description: "Pratiyogita Darpan monthly magazine for competitive exams including UPSC. General knowledge and current affairs.",
    category: "magazines",
    brand: "Pratiyogita Darpan",
    tags: ["pratiyogita darpan", "magazine", "gk", "current affairs", "monthly"],
    language: "hi",
    pageCount: 150,
  },

  // ===== CURRENT AFFAIRS =====
  {
    title: "Speedy Current Affairs 2026 Book PDF",
    slug: "speedy-current-affairs-2026-book",
    description: "Speedy Current Affairs 2026 comprehensive book for UPSC and competitive exams. Covers all important events.",
    category: "current-affairs",
    brand: "Speedy",
    year: 2026,
    language: "both",
    tags: ["speedy", "current affairs", "book", "2026", "gk"],
    pageCount: 500,
  },
  {
    title: "Edu Teria Current Affairs Book 2026 PDF",
    slug: "edu-teria-current-affairs-2026",
    description: "Edu Teria Current Affairs 2026 book for UPSC. Topic-wise coverage with PYQ analysis and practice MCQs.",
    category: "current-affairs",
    brand: "Edu Teria",
    year: 2026,
    tags: ["edu teria", "current affairs", "book", "2026", "upsc"],
    pageCount: 400,
  },
  {
    title: "Daily Current Affairs PDF 2025 — Hindi & English",
    slug: "daily-current-affairs-2025-hindi-english",
    description: "Daily current affairs PDF compilation for UPSC 2025. Updated daily with important news in Hindi and English.",
    category: "current-affairs",
    brand: "Daily CA",
    year: 2025,
    language: "both",
    tags: ["daily current affairs", "2025", "news", "hindi", "english"],
    pageCount: 365,
  },
  {
    title: "Disha Yearly Current Affairs 2023 Compilation PDF",
    slug: "disha-yearly-current-affairs-2023",
    description: "Disha yearly current affairs 2023 compilation for UPSC and competitive exams.",
    category: "current-affairs",
    brand: "Disha",
    year: 2023,
    tags: ["disha", "yearly", "current affairs", "2023", "compilation"],
    pageCount: 300,
  },
  {
    title: "Arihant Yearly Current Affairs 2021 PDF",
    slug: "arihant-yearly-current-affairs-2021",
    description: "Arihant yearly current affairs 2021 compilation for UPSC and competitive exams.",
    category: "current-affairs",
    brand: "Arihant",
    year: 2021,
    tags: ["arihant", "yearly", "current affairs", "2021"],
    pageCount: 400,
  },
  {
    title: "Amar Ujala Newspaper Daily PDF — City-Wise Hindi",
    slug: "amar-ujala-daily-pdf-hindi",
    description: "Amar Ujala Hindi newspaper daily PDF. City-wise editions for UPSC current affairs preparation.",
    category: "current-affairs",
    brand: "Amar Ujala",
    language: "hi",
    tags: ["amar ujala", "newspaper", "hindi", "daily", "current affairs"],
  },
];

async function seed() {
  await mongoose.connect(MONGODB_URI, { dbName: DB_NAME });
  console.log("Connected to MongoDB");

  let inserted = 0;
  let skipped = 0;

  for (const pdf of PDFs) {
    try {
      await PDFModel.findOneAndUpdate(
        { slug: pdf.slug },
        { $setOnInsert: pdf },
        { upsert: true, new: true }
      );
      inserted++;
      console.log(`  ✓ ${pdf.slug}`);
    } catch (err) {
      if (err.code === 11000) {
        skipped++;
      } else {
        console.error(`  ✗ ${pdf.slug}: ${err.message}`);
      }
    }
  }

  console.log(`\nDone. Inserted: ${inserted}, Already existed: ${skipped}`);
  await mongoose.disconnect();
}

seed().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
